//@ts-check

/** @type { HTMLCanvasElement } */
//@ts-ignore This is an HTML Canvas
const CANVAS = document.getElementById("game-canvas");
/**@type {CanvasRenderingContext2D} */
//@ts-ignore
const CTX = CANVAS.getContext("2d");
const happy = document.getElementById("d");
const TXT = document.getElementById("text");
const Output = document.getElementById("names");
const HAN = document.getElementById("Ah");
const VERSE = document.getElementById("a");
const ocean = document.getElementById("b");
const We = document.getElementById("c");
const HEIGHT = 500;
const WIDTH = 890;
CANVAS.height = HEIGHT;
CANVAS.width = WIDTH;
const getRandomIndexs = function (a) {
    let rand = Math.random() * a.length;
    return Math.floor(rand);
};
let getRandomWords = function (a) {
    return a[getRandomIndexs(a)];
};
const generateKt = function (a, ){
    let mk =
        getRandomWords (a) +
    ""
    return mk;
};
const generateKts = function (a, ){
    let mk =
        getRandomWords (a) +
    ""
    return mk;
};
const thusy = [
    "Hellevator - Stray Kids",
    "Double Knot - Stray Kids",
    "Mixtape: Gone Days - Stray Kids",
    "Double Knot (English ver.) - Stray Kids",
    "My Pace (Japanese Ver.) - Stray Kids",
    "Double Knot (Japanese Ver.) - Stray Kids",
    "Levanter (Japanese Ver.) - Stray Kids",
    "Mixtape: On Track - Stray Kids",
    "TOP (Japanese Ver.) - Stray Kids",
    "SLUMP (Japanese Ver.) - Stray Kids",
    "TOP  Stray Kids",
    "TOP (English Ver.) - Stray Kids",
    "Hello Stabger - Stray Kids",
    "Back Door (Japanese Ver.) - Stray Kids",
    "ALL IN (Korean Ver.) - Stray Kids",
    "Going Dumb (with Stray Kids) - Alesso, Stray Kids, Corsak",
    "Mixtape: OH - Stray Kids",
    "Scars - Stray Kids",
    "CALL - Stray Kids",
    "Christmas EveL - Stray Kids",
    "24 to 25 - Stray Kids",
    "Winter Falls - Stray Kids",
    "DOMINO (English Ver.) - Stray Kids",
    "MANIAC (Japanese Ver.) - Stray Kids",
    "Your Eyes - Stray Kids",
    "CIRCUS - Stray Kids",
    "Fairytale - Stray Kids",
    "VENOM (Japanese Ver.) - Stray Kids",
    "Silent Cry (Japanese Ver.) - Stray Kids",
    "Mixtape: Time Out - Stray Kids",
    "CASE 143 (Japanese Ver.) - Stray Kids",
    "THE SOUND - Stray Kids",
    "There - Stray Kids",
    "Like Magic  - Stray Kids, J.Y.Park, ITZY, NMIXX",
    "SUper Bowl (Japanese Ver.) - Stray Kids",
    "Social Path - Stray Kids, LiSA",
    "Butterflies - Stray Kids",
    "All My Life (Stray Kids Remix) - Stray Kids, Lil Durk",
    "WHY? - Stray Kids",
    "lose My Breath (Feat. Charlie Puth) - Stray Kids, Charlie Puth",
    "Chk Chk Boom - Stray Kids",
    "SLASH (From 'DeadPool & Wolverine' - Stray Kids",
    "NIGHT - Stray Kids",
    "Falling Up (English Ver.) - Stray Kids",
    "Falling Up - Stray Kids",
    "Come Play (from the series Arcane League of Legends) - Stray Kids,etc.",
    "Walkin' On Water - Stray Kids",
    "GIANT (Korean Ver.) - Stray Kids",
    "Burnin' Tiers (Changbin & I.N) - Stray Kids",
    "Trunman (Han & Felix) - Stray Kids",
    "ESCAPE (Bang Chan & Hyunjin) - Stray Kids",
    "CIMEMA (Lee Know & Seungmin) - Stray Kids",
    "Hollow - Stray Kids",
    "Parade - Stray Kids",
    "Never Alone - Stray Kids",
    "just a little - Stray Kids",
    "CERMONY  - Stray Kids",
    "CERMONY (KARMA Ver.) - Stray Kids",
    "BEWARE - Stray Kids",
    "Spread My Wings - Stray Kids",
    "YAYAYA - Stray Kids",
    "District 9 - Stray Kids",
    "Mirror - Stray Kids",
    "Grow Up - Stray Kids",
    "My Pace - Stray Kids",
    "Voices - Stray Kids",
    "Question - Stray Kids",
    "M.I.A. - Stray Kids",
    "AWkward Silence - Stray Kids",
    "I am YOU - Stray Kids",
    "Get Cool - Stray Kids",
    "MIROH - Stray Kids",
    "Boxer - Stray Kids",
    "Chronosaurus - Stray Kids",
    "19 - Stray Kids",
    "Side Effects - Stray Kids",
    "TMT - Stray Kids",
    "Double Knot - Stray Kids",
    "Levanter - Stray Kids",
    "Astronaut - Stray Kids",
    "GLOW - Stray Kids",
    "School Life - Stray Kids",
    "4419 - Stray Kids",
    "NOT! - Stray Kids",
    "Awaken - Stray Kids",
    "ROCK - Stray Kids",
    "Grow UP - Stray Kids",
    "3rd Eye - Stray Kids",
    "WHO? - Stray Kids",
    "My Pace - Stray Kids",
    "Vocies - Stray Kids",
    "YOU. - Stray Kids",
    "My Side - Stray Kids",
    "Hero's Soup - Stray Kids",
    "N/S - Stray Kids",
    "0325 - Stray Kids",
    "Entrance - Stray Kids",
    "Victory Song - Stray Kids",
    "Maze of Memories - Stray Kids",
    "Road Not Taken - Stray Kids",
    "Side Effects - Stray Kids",
    "TMT - Stray Kids",
    "Mixtape#1 - Stray Kids",
    "Mixtape#2 - Stray Kids",
    "Mixtape#3 - Stray Kids",
    "Mixtape#4 - Stray Kids",
    "STOP - Stray Kids",
    "Double Knot - Stray Kids",
    "Booster - Stray Kids",
    "Sunshine - Stray Kids",
    "You Can STAY - Stray Kids",
    "GO LIVE - Stray Kids",
    "God's Menu - Stray Kids",
    "Easy - Stray Kids",
    "Pacemaker - Stray Kids",
    "Airplane - Stray Kids",
    "Another Day - Stray Kids",
    "Phobia - Stray Kids",
    "Blue Print - Stray Kids",
    "TA - Stray Kids",
    "Haven - Stray Kids",
    "The Tortosie and the Hare - Stray Kids",
    "Back Door - Stray Kids",
    "B Me - Stray Kids",
    "Any - Stray Kids",
    "Ex - Stray Kids",
    "We Go (Bang Chan, Changbin, HAN) - Stray Kids",
    "Wow (Lee Know, Hyunjin, Felix) - Stray Kids",
    "My Universe - Stray Kids",
    "Easy - Stray Kids",
    "ALL IN - Stray Kids",
    "One Day - Stray Kids",
    "CHEESE - Stray Kids",
    "Thunderous - Stray Kids",
    "DOMINO - Stray Kids",
    "SSKICK - Stray Kids",
    "The Veiw - Stray Kids",
    "Sorry, I Love You - Stray Kids",
    "Silent Cry - Stray Kids",
    "Secret Secret - Stray Kids",
    "Star Lost - Stray Kids",
    "Red Lights (Bang Chan, Hyunjin) - Stray Kids",
    "Surfin' (Lee Know, Changbin, Felix) - Stray Kids",
    "Gone Away (HAN, Seungmin , I.N) - Stray Kids",
    "WOLFGANG - Stray Kids",
    "Awaken - Stray Kids",
    "ROCK - Stray Kids",
    "3rd Eye - Stray Kids",
    "Placebo - Stray Kids",
    "Insomnia - Stray Kids",
    "Behind the Light - Stray Kids",
    "My Side - Stray Kids",
    "0325 - Stray Kids",
    "For You - Stray Kids",
    "Maze of Memories - Stray Kids",
    "Broken Compass - Stray Kids",
    "Hoodie Season - Stray Kids",
    "VENOM - Stray Kids",
    "MANIAC - Stray Kids",
    "Charmer - Stray Kids",
    "FREEZE - Stray Kids",
    "Lonley St. - Stray Kids",
    "Waiting For Us (Bang Chan, Lee Know, Seungmin, I.N) - Stray Kids",
    "Muddy Water (Changbin, Hyunjin, HAN, Felix) - Stray Kids",
    "CASE 143 - Stray Kids",
    "CHILL - Stray Kids",
    "Give Me Your TMI - Stray Kids",
    "SUPER BOARD - Stray Kids",
    "3RACHA (Bang Chan, Changbin, HAN)",
    "TASTE (Lee Know, Hyunjin, Felix) - Stray Kids",
    "Can't Stop (Seungmin, I.N) - Stray Kids",
    "CIRCUS (Korean Ver.) - Stray Kids",
    "FAM (Korean Ver.) - Stray Kids",
    "Connected (Bang Chan) - Stray Kids",
    "Limbo (Lee Know) - Stray Kids",
    "DOODLE (Changbin) - Stray Kids",
    "Love Untold (Hyunjin) - Stray Kids",
    "RUN (HAN) - Stray Kids",
    "Deep End (Felix) - Stray Kids",
    "Stars and Raindrops (Seungmin) - Stray Kids",
    "Hug Me (I.N) - Stray Kids",
    "ZONE (Bang Chan, Changbin, HAN) - Stray Kids",
    "Close (HAN) - Stray Kids",
    "Streetkight (Changbin) - Stray Kids",
    "i hate to admit (Bang Chan) - Stray Kids",
    "I GOT IT (HAN) - Stray Kids",
    "miss you (Hyunjin) - Stray Kids",
    "Maknae On Top (I.N) - Stray Kids",
    "Alien (HAN) - Stray Kids",
    "Because (Changbin, Felix) - Stray Kids",
    "Peice of a Puzzle (Changbin, Seungmin) - Stray Kids",
    "Wish You Back (HAN) - Stray Kids",
    "HaPpy (HAN) - Stray Kids",
    "Up All Night (Bang Chan, Changbin, Felix, Seungmin) - Stray Kids",
    "Drive (Bang Chan, Lee Know) - Stray Kids",
    "ice.cream (Hyunjin) - Stray Kids",
    "THE SOUND - Stray Kids",
    "Battle Ground - Stray Kids",
    "Lost Me - Stray Kids",
    "DLMLU - Stray Kids",
    "Novel - Stray Kids",
    "Scars - Stray Kids",
    "There - Stray Kids",
    "Hall of Fame - Stray Kids",
    "S-Class - Stray Kids",
    "ITEM - Stray Kids",
    "Super Bowl - Stray Kids",
    "TOPLINE (Feat. Tiger JK) - Stray Kids, Tiger JK",
    "DLC - Stray Kids",
    "GET LIT - Stray Kids",
    "Collision - Stray Kids",
    "FNF - Stray Kids",
    "Youtiful - Stray Kids",
    "THE SOUDN (Korean Ver.) - Stray Kids",
    "Mixtape:Tiem Out - Stray Kids",
    "MEGAVERSE - Stray Kids",
    "LALALALA - Stray Kids",
    "BLIND SPOT - Stray Kids",
    "COMFLEX - Stray Kids",
    "Cover Me - Stray Kids",
    "Leave - Stray Kids",
    "MOUNTAINS - Stray Kids",
    "JJAM - Stray Kids",
    "I Like It - Stray Kids",
    "Runners - Stray Kids",
    "twilight - Stray Kids",
    "GIANT - Stray Kids",
    "NIGHT - Stray Kids",
    "Saiyan - Stray Kids",
    "Christmas Love - Stray Kids",
    "NIGHT (English Ver.) - Stray Kids",
    "Walkin' On Water - Stray Kids",
    "Bounce Back - Stray Kids",
    "U (Feat. TABLO) - Stray Kids, TABLO",
    "Railway (Bang Chan) - Stray Kids",
    "Unfair (Felix) - Stray Kids",
    "HALLUCINATION (I.N) - Stray Kids",
    "Youth (Lee Know) - Stray Kids",
    "So Good (Hyunjin) - Stray Kids",
    "ULTRA - Stray Kids",
    "Hold my Hand (HAN) - Stray Kids",
    "As we are (Seungmin) - Stray Kids",
    "BLEEP - Stray Kids",
    "CEREMONY - Stray Kids",
    "CREED - Stray Kids",
    "MESS - Stray Kids",
    "In My Head - Stray Kids",
    "Half Time - Stray Kids",
    "Phoneix - Stray Kids",
    "Ghost - Stray Kids",
    "0801 - Stray Kids",
    "Blue Orangeade - Tomorrow x Together",
    "CROWN - Tomorrow x Together",
    "Our Summer - Tomorrow x Together",
    "Cat & Dog - Tomorrow x Together",
    "Nap of a star - Tomorrow x Together",
    "Cat & Dog (English Ver.) - Tomorrow x Together",
    "Our Summer (Acousitic Ver.) - Tomorrow x Together",
    "Anegl Or Devil (Japanese Ver.) - Tomorrow x Together",
    "Drama - Tomorrow x Together",
    "Can't You See Me? - Tomorrow x Together",
    "Fairy of Shamppoo - Tomorrow x Together",
    "Maze in the Mirror - Tomorrow x Together",
    "PUMA - Tomorrow x Together",
    "Eternally - Tomorrow x Together",
    "Drama (Japanese Ver.) - Tomorrow x Together",
    "Ghosting - Tomorrow x Together",
    "Blue Hour - Tomorrow x Together",
    "We Lost The Summer - Tomorrow x Together",
    "Wishlist - Tomorrow x Together",
    "Way Home - Tomorrow x Together",
    "Your Light - Tomorrow x Together",
    "Your Light (Japanese Ver.) - Tomorrow x Together",
    "Your LIght (Instrumental) - Tomorrow x Together",
    "Force - Tomorrow x Together",
    "Love Sight - Tomorrow x Together",
    "Love Sight (Instrumental) - Tomorrow x Together",
    "OX1=LOVESONG(I Know I Love You) feat. pH-1, Woodie Gochild, Seori - Tomorrow x Together",
    "OX1=LOVESONG(I Know I Love You) feat. MOD SUN - Tomorrow x Together",
    "Ito - Tomorrow x Together",
    "EYES (from 'Aemored Saurus') - Tomorrow x Together",
    "OX1=LOVESONG (I Know I Love You) Japanese Ver. - Tomorrow x Together",
    "Ito - Tomorrow x Together",
    "MOA Diary (Dubaddu Wari Wari) Japanese Ver.  - Tomorrow x Together",
    "Magic - Tomorrow x Together",
    "Opening Sequence - Tomorrow x Together",
    "Good Boy Gone Bad - Tomorrow x Together",
    "Trust Fund Baby - Tomorrow x Together",
    "Lonley Boy (The tattoo on my ring finger) - Tomorrow x Together",
    "Thursday's Child Has Far To Go - Tomorrow x Together",
    "Valley of Lies - Tomorrow x Together",
    "Good Boy Gone Bad (Japanese Ver.) - Tomorrow x Together",
    "Free Falling - Tomorrow x Together",
    "Devil by the Window - Tomorrow x Together",
    "Sugar Rush Ride - Tomorrow x Together",
    "Happy Fools (feat. Coi Leray) - Tomorrow x Together, Coi Leray",
    "Tinnitus (Wanna be a Rock) - Tomorrow x Together",
    "Farewell, Neverland - Tomorrow x Together",
    "Goodbye Now - Tomorrow x Together",
    "Goodbye Now (Instrumental) - Tomorrow x Together",
    "Sugar Rush Ride (Japanese Ver.) - Tomorrow x Together",
    "Do It Like That  - Tomorrow x Together",
    "Do It Like That (Jersey Club Remix) - Tomorrow x Together",
    "Do It Like That (Pop R&B Remix) - Tomorrow x Together",
    "Do It Like That (Alan Walker Remix) - Tomorrow x Together",
    "Do It Like That (Jax Jones Remix) - Tomorrow x Together",
    "Back For More (with Anitta) - Tomorrow x Together, Anitta",
    "Back For More (TXT Ver.) - Tomorrow x Together, Anitta",
    "Deja Vu (Japanese Ver.) - Tomorrow x Together",
    "Open Always Wins - Tomorrow x Together",
    "Heaven - Tomorrow x Together",
    "Over the Moon - Tomorrow x Together",
    "Danger - Tomorrow x Together",
    "Resist (Not Gonna Run Away) - Tomorrow x Together",
    "Forty One Winks - Tomorrow x Together",
    "Higer Than Heaven - Tomorrow x Together",
    "Love Story - Tomorrow x Together",
    "Rise - Tomorrow x Together",
    "Love Language - Tomorrow x Together",
    "When Day Comes - Tomorrow x Together",
    "Step By Step - Tomorrow x Together",
    "butterflies (feat. TAEHUN & Kim Chaewon of LE SSERAFIM) - Tomorrow x Together, JVKE, LE SSERAFIM, TAEHUN, KIM CHAEWON",
    "New Rules - Tomorrow x Together",
    "9 and Three Quarters (Run Away) - Tomorrow x Together",
    "Roller Coaster - Tomorrow x Together",
    "Poppin' Stars - Tomorrow x Together",
    "Can't We Just Leave The Monster Alive - Tomorrow x Together",
    "Magic Island - Tomorrow x Together",
    "20cm - Tomorrow x Together",
    "Angel Or Devil - Tomorrow x Together",
    "Intro: DREAMING - Tomorrow x Together",
    "Force - Tomorrow x Together",
    "Outro: STILL - Tomorrow x Together",
    "Anti-Romantic - Tomorrow x Together",
    'OX1=LOVESONG (I Know I Love YOU) feat. Seori - Tomorrow x Together, Seori',
    "Magic - Tomorrow x Together",
    "Ice Cream - Tomorrow x Together",
    "What if I had been that PUMA - Tomorrow x Together",
    "No Rules - Tomorrow x Together",
    "Dear Sputnik - Tomorrow x Together",
    "Frost - Tomorrow x Together",
    "Lo$er=L<3ver - Tomorrow x Together",
    "Intro: FLOATING- Tomorrow x Together",
    "Outro: FALLING - Tomorrow x Together",
    "Growing Pain- Tomorrow x Together",
    "Chasing That Feeling - Tomorrow x Together",
    "Back For More (TXT Ver.) - Tomorrow x Together",
    "Dreamer - Tomorrow x Together",
    "Happily Ever After - Tomorrow x Together",
    "Skipping Stones - Tomorrow x Together",
    "Blue Spring - Tomorrow x Together",
    "Do It Like That - Tomorrow x Together",
    "I'll See You There Tomorrow - Tomorrow x Together",
    "- --- -- ---.-.-.---.-- - Tomorrow x Together",
    "Deja Vu - Tomorrow x Together",
    "Miracle - Tomorrow x Together",
    "The Killa (I Belong to You) - Tomorrow x Together",
    "Quarter Life - Tomorrow x Together",
    "Upside Down Kiss  - Tomorrow x Together",
    "Beautiful Strangers - Tomorrow x Together",
    "Ghost Girl - Tomorrow x Together",
    "Sunday Driver - Tomorrow x Together",
    "Dance With You - Tomorrow x Together",
    "Take My Half - Tomorrow x Together",
    "Bird Of Night - Tomorrow x Together",
    "Song Of Stars - Tomorrow x Together",
    "Beautiful Staranger (Japansese Ver.) - Tomorrow x Together",
    "Sara - We Three",
    "Hell As Well - We Three",
    "If I Loved a Boy - We Three",
    "Secrets - We Three",
    "Daydreams - We Three",
    "Exes Flowers - We Three",
    "In Therapy - We Three",
    "Bad Ass Bitch - We Three",
    "Body Fat Percentage - We Three",
    "HALF HEARTED - We Three",
    "She's Got That  - We Three",
    "Same Way Too - We Three",
    "Lifeline - We Three",
    "Heaven's Not Too Far - We Three",
    "Six Feet Deep - We Three",
    "i wanna love somebody - We Three",
    "30,000 ft - We Three",
    "Confident - We Three",
    "Bad Guy - We Three",
    "3 Am - We Three",
    "Superman - We Three",
    "You and I - We Three",
    "Machine - We Three",
    "hold me, baby - We Three",
    "So They Say - We Three",
    "Fall For You - We Three",
    "Insomniac - We Three",
    "Nothing Else Matters - We Three",
    "Kissin' When We're Mad - We Three",
    "Fairytale - We Three",
    "Running - We Three",
    "Fire Away - We Three",
    "Our Last Christmas Eve - We Three",
    "Testify - We Three",
    "Makeup - We Three",
    "Dancing In The Dark - We Three",
    "Full Time Job - We Three",
    "Hold On - We Three",
    "You Space and Time - We Three",
    "Nightlight - We Three",
    "Sweater Weather - We Three",
    "Timeless - We Three",
    "Stuck Like This - We Three",
    "Dear PARANOIA - We Three",
    "mid July - We Three",
    "when i'm with you - We Three",
    "couch - We Three",
    "Us - We Three",
    "insecure - We Three",
    "Chase Me - We Three",
    "OVERDOSE - We Three",
    "Broke in two - We Three",
    "Sincerly, ME - We Three",
    "Body Fat Percentage - We Three",
    "If I Saw You - We Three",
    "Happy - We Three",
    "Full Time Job - We Three",
    "Bad at Love - We Three",
    "Love Me In A Circle - We Three",
    "When I'm with You - We Three, Noah Guthrie",
    "Paradise - We Three",
    "Full Tiem Job (Live) - We Three",
    "Bas ass Bitch (Live) - We Three",
    "Same Way Too (Live) - We Three",
    "She's Got That (Live) - We Three",
    "Bad Guy (Live) - We Three",
    "Daydreams (Live) - We Three",
    "You Space And Time (Live) - We Three",
    "Heaven's Not Too Far (Live) - We Three",
    "Lifeline (Live) - We Three",
    "Half Hearted (Live) - We Three",
    "Insomnic (Live) - We Three",
    "3AM / Overdose (Live) - We Three",
    "Sara (Live)  - We Three",
    "I Wanna Love Somebody (Live) - We Three",
    "Kissin' When We're Mad (Live) - We Three",
    "Somebody Once Told Me (Live) - We Three",
    "God Things  - We Three",
    "50 Shades of Pink - We Three",
    "i wrote this song in your lap - We Three",
    "Glow - Big Ocean",
    "BLOW- Big Ocean",
    "SLOW (Feat. Young K (Day 6))- Big Ocean, Young K",
    "brighT- Big Ocean",
    "SINKING- Big Ocean",
    "FADE OUT- Big Ocean",
    "ATTENTION- Big Ocean",
    "END OF TIME- Big Ocean",
    "BUCKET HAT- Big Ocean",
    "Multiverse - 1verse",
    "Shatterd (ENG ver.)- 1verse",
    "Shatterd (KOE ver.) - 1verse",
    "Here's Your Love Song - TX2, Chase Elliot, Mantra Beats",
    "Living Punk Rock - TX2",
    "Harpoon - TX2",
    "Not Me - TX2",
    "No Place Like Home - TX2",
    "Nail In The Coffin - TX2",
    "Step Over A Body - TX2",
    "Vampire By Rumor - TX2",
    "Fuck It All - TX2",
    "Thank You For... - TX2",
    "TRUST NO ONE - TX2",
    "Drop Dead - TX2",
    "Where'd U Come From - TX2",
    "Pull The Plug - TX2",
    "Heaven Was Full(I'm Headed Straight To Hell) - TX2",
    "A Choice - TX2",
    "Flowers - TX2",
    "Two Pills - TX2",
    "I Would Hate Me Too - TX2",
    "Randy McNally(No Love Like Christan Hate) - TX2",
    "Say You're Insercure (Without Saying It) - TX2",
    "Loaded Guns - TX2",
    "The Witching Hour - TX2",
    "Antidote - TX2",
    "Animal - TX2",
    "Walking Dead Man - TX2",
    "Sex Sells (Hard) - TX2",
    "Degrade Me - TX2",
    "Black Weeding - TX2",
    "Am I A Ghost - TX2",
    "6 Seconds Left - TX2",
    "Burn - TX2",
    "So Numb - TX2",
    "Vendetta (feat. Johnny 3 Tears) - TX2, Johnny 3 Tears",
    "Hatchet - TX2",
    "Swing At Me - TX2",
    "MAD (Feat. Ice Nine Kills) - TX2, Ice Nine Kills",
    "Swing At Me - TX2",
    "THIS ISN'T ABOUT DRUGS (I SWEAR) Feat. From First To Last - TX2",
    "Cruel World - TX2",
    "Violent Nature - TX2",
    "Cry - TX2, Hopelessly Devoted To You",
    "Infamous - TX2",
    "HOSTAGE (they will not erase us) - TX2",
    "Hollow Frame - TX2",
    "Feed (feat. DeathbyRomy) - TX2, DeathbyRomy",
    "Nice Guy (feat. Ekoh) - TX2, Ekoh",
    "run it up - bbno$, slightbeats",
    "damn - bbno$, Lzr",
    "lets go - bbno$",
    "thots - bbno$, MIA GLADSTONE, Cig.Margot",
    "mmmyea - bbno$, Trippy tha Kid",
    "lit like candle - bbno$, nowill",
    "Pay Attention - bbno$",
    "bandaid - bbno$",
    "how i do - bbno$, Cig.Margot, Al Rocco",
    "run this shit - bbno$, Yung Gray, downtime",
    "benihana (ft. yung gravy prod.sonn) - bbno$, yung gravy, prod.sonn",
    "Boomin - bbno$, yung gravy",
    "zoom - bbno$, hollow",
    "wonkybish - bbno$, Trippy tha Kid, Senojnayr",
    "scooter - bbno$, Lzr, AKAY",
    "Whippin - bbno$, yung gravy",
    "ferrari fitness - bbno$, Futon, lentra",
    "dunkaroos - bbno$, Lzr",
    "what hook? - bbno$, Trippy tha Kid, howl",
    "lickity split - bbno$, Trippy tha Kid, hollow",
    "coasting - bbno$, hollow, Futon",
    "politics - bbno$, Creepa, Trippy tha Kid",
    "Rosisserie - bbno$, yung gravy",
    "Gasoline (feat. Young King Dave) - bbno$, yung gravy, Young King Dave",
    "Gold (feat. Mia Gladstone) - bbno$, yung gravy",
    "Whippin - bbno$, yung gravy",
    "Boomin - bbno$, yung gravy",
    "skrrrr - bbno$, Max Wellls, Cig.Margot, Lzr",
    "ploy - bbno$",
    "what i do - bbno$, Yung bambi, lentra",
    "who dat boi - bbno$, lentra, So Loki",
    "I - bbno$",
    "semi auto - bbno$, Hounds, Trippy tha Kid",
    "What a Day! - bbno$, funton Don",
    "Too Much Yello - bbno$, ROSHIMA",
    "super saiyan flex - bbno$, Al Rocco, yung castor, 8mc",
    "3mo - bbno$, lentra",
    "litmas - bbno$, Lzr",
    "golden rule - bbno$, downtime",
    "drip - bbno$, jellorio",
    "moneytalk - bbno$, Julez",
    "WYWD - bbno$, Julez",
    "lavish - bbno$, hollow",
    "tony thot - bbno$, lentra",
    "too easy - bbno$, downtime",
    "tokyo glo remix - bbno$, Raka, LMC",
    "moves - bbno$, lentra",
    "fragile - bbno$, So Loki",
    "bubblin - bbno$, So Loki",
    "swagu - bbno$, So Loki",
    "more concrete - bbno$, So Loki",
    "okay - bbno$, So Loki",
    "checkmate - bbno$, So Loki",
    "money conversation - bbno$, Y2K",
    "Mr.Miyagi - bbno$, andrei, Waka Flocka Flame",
    "thankful - bbno$, Y2K, Lewis Grant",
    "jurassic - bbno$, lentra, TrippyThaKid",
    "doubles - bbno$, Swerzie, Downtime",
    "shinning - bbno$, lentra",
    "With Ease - bbno$, Billy Marchiafava, ANH",
    "hyrule temple - bbno$, DJ Yung Vamp",
    "sriracha - bbno$, lentra",
    "pouch - bbno$, Y2K",
    "cheesy - bbno$, Warhol.SS, Dilip",
    "Bad Boy - bbno$, Yung Bae, Billy Marchiafava",
    "Lalala - bbno$, Y2K",
    "slop - bbno$",
    "Lalala (Polyphina Remix) - bbno$, Y2K, Polyphina",
    "Lalala (Oliver Heldens Remix) - bbno$, Y2K, Oliver Heldens",
    "Lalala (IIkan Gunuc Remix) - bbno$, Y2K, IIkan Gunuc",
    "Lalala (Remic - [feat. Enrique Iglesias & Carly Rae Jepson]) - bbno$, Y2K, Enrique Iglesias, Carley Rae Japson",
    "shinning on my ex - bbno$, Yung Gravy",
    "iunno - bbno$, BABY GRAVY, Yung Gravy",
    "Welcome to Chilis - bbno$, BABY GRAVY, Yung Gravy",
    "Off The Goop - bbno$, BABY GRAVY, Yung Gravy, Cuco",
    "out of control - bbno$, ceo@business.net, lentra",
    "Diva Bonita - bbno$, SwuM",
    "Viscaity - bbno$, SwuM",
    "Lamb Kabob - bbno$, SwuM",
    "Voodo - bbno$, SwuM",
    "Big Racks - bbno$, SwuM",
    "mememe - bbno$, lentra",
    "quarantine freestyle - bbno$, lentra",
    "what would baby do? - bbno$, lentra",
    "astrology - bbno$, lentra",
    "jack money bean - bbno$, Yung Gravy, lentra",
    "imma - bbno$, lentra",
    "backwards - bbno$, lentra",
    "Wawawa - bbno$, Y2K",
    "help herself - bbno$, Diamond Pistols",
    "bad to the bone - bbno$. lentra",
    "sorry - bbno$",
    "my oh my - bbno$",
    "wussup - bbno$, Yung Gravy",
    "edamame - bbno$, Rich Brown",
    "take a trip - bbno$, ceo@business.net, jungle bobby, lentra",
    "i remember - bbno$",
    "yoga - bbno$, Rebecca Black",
    "brainless - bbno$, lentra",
    "big boss baby - bbno$, lentra",
    "mathematics - bbno$",
    "piccolo - bbno$",
    "pogo - bbno$, Diplo",
    "sophisticated - bbno$",
    "C'est La Vie (with bbno$ & Rich Brian) - bbno$, Yung Gravy, Rich Brian",
    "top gun - bbno$",
    "i see london i see france - bbno$",
    "help herself (dnb remix) ~ spotify singles - bbno$",
    "feel good inc (bbno$ re-finessed) ~ spotify singles - bbno$",
    "still - bbno$",
    "Not A Beanie - bbno$, Connor Price",
    "Ushme Uturbe - bbno$, Kalush Orchestra, DITVAK, KALUSH",
    "Goodness Graciuos - bbno$, BABY GRAVY, Yung Gravy",
    "You Need Jesus - bbno$, BABY GRAVY, Yung Gravy",
    "Ticking Away - bbno$, VALORANT, Grabbitz",
    "It Happpens (feat. bbno$) - bbno$, Little Big",
    "Nightmare on Peachtree Street (feat. Freddie Dredd) - bbno$, Yung Gravy, Freddie Dredd, BABY GRAVY",
    "Girlfriend - bbno$, Party Pupils, MAX, MILLI",
    "SOS - bbno$, KnowKnow",
    "Washed (feat. bbno$) - bbno$, Tiny Meat Gang",
    "TANGO - bbno$, Tommy Cash",
    "lil' freak - bbno$",
    "it boy - bbno$",
    "two - bbno$",
    "meant to be - bbno$",
    "check - bbno$",
    "antidepressants - bbno$",
    "boom - bbno$",
    "mary poppins - bbno$",
    "1-800 - bbno$, Ironmouse",
    "hot topic - bbno$",
    "in my zone - bbno$, VALORANT",
    "NSFW - bbno$",
    "FIGHT OR FLIGHT - bbno$, Zoey808",
    "yezzir - bbno$",
    "flex - bbno$, Sonn",
    "guarantee - bbno$, Sonn",
    "bad girl - bbno$, lentra, BAINS",
    "bulletproof - bbno$, lentra",
    "don't tell me shit - bbno$, lentra",
    "pennies up - bbno$, MIA GLADSTONE, Mr. Carmack, Promnite",
    "namaste - bbno$, Trippy Tha Kid, JASON RICH",
    "opus - bbno$, lentra, Juelz, So Loki",
    "jurassic - bbno$, lentra, TrippyThaKid",
    "banna - bbno$, lenta",
    "stucco - bbno$, lentra",
    "doubles - bbno$, Swerzie, Downtime",
    "roo doo - bbno$, lentra",
    "bunk - bbno$, lentra, Swerzie",
    "nursery - bbno$, lentra",
    "shinning - bbno$, lentra",
    "chess - bbno$, Konrad OldMoney",
    "seven - bbno$, TrippyThaKid, hollow",
    "thankful - bbno$, Y2K, Lewis Grant",
    "bad thoughts - bbno$",
    "on god - bbno$, Lewis Grant",
    "slop - bbno$",
    "shinning on my ex - bbno$, Yung Gravy",
    "I DON'T CARE CAUSE I GOOT MONEY!!!!!! - bbno$",
    "pop song - bbno$",
    "jimmy neutron - bbno$, LIL MAYO",
    "pouch - bbno$",
    "it gon'last - bbno$",
    "gone - bbno$",
    "Bandsville - bbno$, BABY GRAVY, Yung Gravy",
    "Justin Bieber Wrist - bbno$, BABY GRAVY, Yung Gravy",
    "Go Banannas - bbno$, BABY GRAVY, Yung Gravy, Spark Master Tape",
    "Off The Goop - bbno$, BABY GRAVY, Yung Gravy, Cuco",
    "Gasoline, Pt.2 - bbno$, BABY GRAVY, Yung Gravy, Spark Master Tape",
    "Welcome to Chillis - bbno$, BABY GRAVY, Yung Gravy",
    "Cadbury Creme - bbno$, BABY GRAVY, Yung Gravy, TrippyThaKid",
    "iunno - bbno$, BABY GRAVY, Yung Gravy",
    "Myrtle Beach Summer 1974 - bbno$, BABY GRAVY, Yung Gravy",
    "shinning on my ex - bbno$, BABY GRAVY, Yung Gravy",
    "rgb money - bbno$, lentra, Crosby",
    "astrology - bbno$, lentra",
    "admit it - bbno$, lentra TrippyThaKid",
    "keep up - bbno$, lentra, TrippyThaKid",
    "jack money bean - bbno$, Yung Gravy, lentra",
    "backwards - bbno$, lentra",
    "bubbles - bbno$, lentra, Crosby",
    "mahogany - bbno$, lentra",
    "man in the mirror - bbno$, lentra",
    "on one - bbno$, Blow Fever, ceo@business.net, lentra",
    "feeling good - bbno$, lentra, Gooch",
    "resume - bbno$",
    "black eyed peas - bbno$",
    "brainless - bbno$, lentra",
    "u mad! - bbno$",
    "2 time zones - bbno$, Night Lovell",
    "check up - bbno$, lentra",
    "i remember - bbno$",
    "tonight we fuckin' party - bbno$, ANH",
    "bag o die - bbno$",
    "chipotle - bbno$",
    "touch grass (feat. Yung Gravy) - bbno$, Yung Gravy",
    "let em know  - bbno$",
    "piccolo - bbno$",
    "robet patekson - bbno$",
    "b to the b - bbno$",
    "deadman (feat. Lil Toe) - bbno$, Lil Toe",
    "vasectomy - bbno$",
    "e-girl anthem - bbno$",
    "No Way Jose - bbno$, BABY GRAVY, Yung Gravy",
    "Super Smash Bros. - bbno$, BABY GRAVY, Yung Gravy",
    "back 2 back 2 back - bbno$, BABY GRAVY, Yung Gravy",
    "Pasadena - bbno$, BABY GRAVY, Yung Gravy",
    "You Need Jesus - bbno$, BABY GRAVY, Yung Gravy",
    "Onomatopeia - bbno$, BABY GRAVY, Yung Gravy",
    "swiper no swiping! - bbno$, BABY GRAVY, Yung Gravy",
    "Despicable G's - bbno$, BABY GRAVY, Yung Gravy",
    "Goodness Graciuos - bbno$, BABY GRAVY, Yung Gravy",
    "Touch Grass - bbno$, BABY GRAVY, Yung Gravy",
    "gigolo - bbno$",
    "Asthma Attack - NOAHFINNCE",
    "Underachiever - NOAHFINNCE",
    "STUPID - NOAHFINNCE",
    "parents (feat. Doll Skin) - NOAHFINNCE, DOll Skin",
    "LIFE'S A BIT - NOAHFINNCE",
    "PITY - NOAHFINNCE",
    "MIND BLANK NO THOUGHTS - NOAHFINNCE",
    "KICKIN TRASH - NOAHFINNCE",
    "WEIRDOS - NOAHFINNCE",
    "Clearveiw - NOAHFINNCE, Sophie Powers",
    "WORMS (In My Brain) - NOAHFINNCE",
    "I JUST WON'T CARE - NOAHFINNCE",
    "BETTER DAYS - NOAHFINNCE",
    "CHASHING DAYLIGHT - NOAHFINNCE",
    "TELL ME THAT YOU'RE OKAY - NOAHFINNCE",
    "AFTER THERAPY (feat. Hot Mulligan) - NOAHFINNCE, Hot Mulligan, Extra Large Holiday Card",
    "LALALA - NOAHFINNCE",
    "(NOT A) LOVE SONG - NOAHFINNCE, SOAP",
    "SEWN SHUT - SOAP",
    "No Point Pretending (Song For Tour) - NOAHFINNCE, Bears in Trees",
    "I KNOW BETTER - NOAHFINNCE",
    "GROWING UP ON THE INTERNET - NOAHFINNCE",
    "SCUMBAG - NOAHFINNCE",
    "Today - NOAHFINNCE, Rare Americans",
    "I Miss Having Sex But At Least I Don't Wanna Die Anymore - NOAHFINNCE, Hopelessly Devoted To You",
    "Boygirl - NOAHFINNCE, Pollyanna",
    "KINDA LOVE IT - NOAHFINNCE",
    "3 DAY HEADACHE - NOAHFINNCE",
    "ALEXITHYMIA - NOAHFINNCE",
    "SUBTITLES - NOAHFINNCE",
    "RISE AND GRING - NOAHFINNCE",
    "ALL THE SAME/NOT THE SAME - NOAHFINNCE",
    "SCUMBAG - NOAHFINNCE",
    "LOVELY LADIES - NOAHFINNCE",
    "GIBBERISH",
    "The Judge - NOAHFINNCE",
    "Chama La - AJR, T'y R.B, Houdini",
    "Celebrate - AJR, Ingrid Michaelson",
    "The Lotto - AJR, Ingrid Michaelson",
    "I'm Ready - AJR",
    "Woody Allen - AJR",
    "Growing Old On Bleeker Street - AJR",
    "AfterHours - AJR",
    "Buy You a Rose - AJR",
    "Infinity - AJR",
    "Alice by the Hudson - AJR",
    "Pitchforck Kids - AJR",
    "3AM - AJR",
    "Let The Games Begin - AJR",
    "Come Hang Out - AJR",
    "Weak - AJR",
    "Turing Out - AJR",
    "I'm Not Famous - AJR",
    "No Grass Today - AJR",
    "It's On Us (Benefiting the 'It's On Us' Campaign) - AJR",
    "Drama (Recorded at Spotify Studios NYC) - AJR",
    "Location (Recorded at SPotify Studios NYC) - AJR",
    "Pretender (feat. Lil Yachty & AJR) - AJR, Steve Aoki, Lil Yachty",
    "Dear Winter 2.0 - AJR",
    "Bang! (feat. Hayley Kiyoko-AhhHaa Remix) - AJR, Hayley Kiyoko, AhhHaa",
    "World's Smallest Violin (Sped Up) - AJR",
    "All My Favorite Songs (feat. AJR) - AJR, Weezer",
    "Way Less Sad - AJR",
    "Redord Player (with AJR) - AJR, Daisy the Great",
    "Weak (Nicolas Julian Remix) - AJR, Nicolas Julian",
    "I Won't - AJR",
    "The DJ Is Crying For Help - AJR",
    "The Dumb Song - AJR",
    "God is Really Real - AJR",
    "Yes I'm A Mess - AJR",
    "Betty - AJR",
    "The Plane That Never Lands - AJR",
    "A Dog Song - AJR",
    "I'm Sorry You Went Crazy - AJR",
    "The Big Goodbye - AJR",
    "Overture (Living Room) - AJR",
    "Infinity - AJR",
    "I'm Ready - AJR",
    "My Calling - AJR",
    "Thirsty - AJR",
    "Pitchfork Kids - AJR",
    "Woody Allen - AJR",
    "Livin' On Love - AJR",
    "Big White Bed - AJR",
    "The World Is A Marble Heart - AJR",
    "The Green And The Town - AJR",
    "Big Idea - AJR",
    "Growing Old On Bleeker Street - AJR",
    "Overture (The Click) - AJR",
    "Weak - AJR",
    "Sober Up (feat. Rivers Cuomo) - AJR, Rivers Cuomo",
    "Drama - AJR",
    "Turning Out - AJR",
    "No Grass Today - AJR",
    "Three-Thirty - AJR",
    "Call My Dad - AJR",
    "I'm Not Famous - AJR",
    "Netflix Trip - AJR",
    "Bud Like You - AJR",
    "Come Hang Out - AJR",
    "Burn The House Down - AJR",
    "Role Models - AJR",
    "Normal - AJR",
    "Next Up Forever - AJR",
    "Birthday Party - AJR",
    "100 Bad Days - AJR",
    "Don't Throw Out My Legos - AJR",
    "Break My Face - AJR",
    "The Entertainment's Here - AJR",
    "Karma - AJR",
    "Beats - AJR",
    "Wow, I'm Not Crazy - AJR",
    "Dear Winter - AJR",
    "Finale (Can't Wait To See What You Do Next) - AJR",
    "OK Overture - AJR",
    "Bummerland - AJR",
    "3 O'Clock Things - AJR",
    "My Play - AJR",
    "Joe - AJR",
    "Adventure Out There",
    "Bang! - AJR",
    "The Trick - AJR",
    "Ordinaryish People (feat. Blue Man Group) - AJR, Blue Man Group",
    "Humpty Dumpty - AJR",
    "Way Less Sad - AJR",
    "Christmas In June - AJR"
]
const yoongbook = [
    "Felix From Stray Kids",
    "Felix From Stray Kids",
    "Felix From Stray Kids",
    "Felix From Stray Kids",
    "Han From Stray Kids",
    "Bang Chan From Stray Kids",
    "I.N. From Stray Kids",
    "Lee Know From Stray Kids",
    "Hyunjin From Stray Kids",
    "Seungmin From Stray Kids",
    "Yeonjun From TXT",
    "Soobun From TXT",
    "Beomgyu From TXT",
    "Tarhyun From TXT",
    "Huening Kai (Not Carlisle Jr.) From TXT",
    "S.Coups From Seventeen",
    "Jeonghan From Seventeen",
    "Joshua From Seventeen",
    "Jun From Seventeen",
    "Hosi From Seventeen",
    "Wonwoo From Seventeen",
    "Woozi From Seventeen",
    "DK From Seventeen",
    "Mingyu From Seventeen",
    "The8 From Seventeen",
    "Seungkwan From Seventeen",
    "Vernon From Seventeen",
    "Dino From Seventeen",
    "Hongjoong From Ateez",
    "San From Ateez",
    "Jongho From Ateez",
    "Seonghwa From Ateez",
    "Yunho From Ateez",
    "Yeosang From Ateez",
    "Mingi From Ateez",
    "Wooyoung From Ateez",
    "Kim Ji-seok From Big Ocean",
    "Lee Chan-yeon From Big Ocean",
    "PJ From Big Ocean ",
    "Hyuk From 1verse",
    "Seok From 1verse",
    "Nathan From 1verse",
    "Kenny From 1verse",
    "Aito From 1verse",
    "Ni-Ki From Enhypen",
    "Sunghoon From Enhypen",
    "Heeseung From Enhypen",
    "Jake From Enhypen",
    "Jay From Enhypen",
    "Jungwon From Enhypen",
    "Sunoo From Enhypen",
    "Son Jun-hyung From GHOST9",
    "Lee Shin From GHOST9",
    "Lee Kang-sung From GHOST9",
    "Choi Jun-seong From GHOST9",
    "Prince From GHOST9",
    "Lee Woo-jin From GHOST9",
    "Lee Jin-woo From GHOST9",
    "Hwang Dong-jiun From GHOST9",
    "Lee Tae-seung From GHOST9",
    "Kim Ji-woong From Zerobaseone",
    "Zhang Hao From Zerobaseone",
    "Sung Han-bin from Zerobaseone",
    "Seok Matthew From Zerobaseone",
    "Kim Tae-rae From Zerobaseone",
    "Ricky From Zerobaseone",
    "Kim Gyu-vin From Zerobaseone",
    "Park Gun-wook From Zerobaseone",
    "Haru From XLOV",
    "Hyun From XLOV",
    "Rui From XLOV",
    "Wumuti From XLOV",
    "Kamden From Ampers&One",
    "Brian From Ampers&One",
    "Jiho From Ampers&One",
    "Siyun From Ampers&One",
    "Kyrell From Ampers&One",
    "Mackiah From Ampers&One",
    "Seungmo From Ampers&One",
    "Seongil From 82major",
    "Yechan From 82major",
    "Seongmo From 82major",
    "Seongbin From 82major",
    "Seokjoon From 82major",
    "Dogyun From 82major",
    "Jin From BTS",
    "Suga From BTS",
    "J-Hope From BTS",
    "RM From BTS",
    "Jimin From BTS",
    "V From BTS",
    "Jung Kook From BTS",
    "Jun. K From 2PM",
    "Ok Taec-yeon From 2PM",
    "Jang Wooyoung From 2PM",
    "Lee Jun-ho From 2PM",
    "Hwang Chan-sung From 2PM",
    "Mark Tuan From Got7",
    "Jay B From Got7",
    "Jackson Wang From Got7",
    "Jinyoung From Got7",
    "Choi Young-jae From Got7",
    "BamBam From Got7",
    "Yugyeom From Got7"
]
const Kenny =  [
	"He was eating toast plain toast with nothing on it have you ever seen someone eat toast with nothing on it haowing truly",
	"Almost plumting to death in front of a stadium of screaming pepole is alawys a warning sign in a cosntant prade of warning signs latley that I need more sleep",
	"You better act like the sunshine out of his dick and you better make me belive it",
	"I am gulity of loving you",
	"The only problem is I want to be toching him back everywere",
	"Yay Arson",
	"Fine it was a pharmisotcal company whose dugs let me be very clear have not proven to have killed any children at all",
	"Step one is ganing the ducks trust",
	"Te Quireo no not te quireo te amo te amo te amo",
	"Angle is lying on the floor and not moving",
	"Fuck Zach",
	"I am head over heels in love with you too",
	"And not geting to relive the best kiss of my life is a prety big incovinnce",
	"My world was reduced to his my best friend my lover my.... fiance",
	"Just as I feel the police slam into me my day resits",
	"I am not going to let you commit arson...... today",
	"Stella Storino bought me weed!!!",
	"And zeke may have given me an edible. WHEN DID ZEKE GIVE YOU AN EDIBLE",
	"KISS ME HARD.. 'I want my cheer sweatshirt back'",
	"Are going to jail for stealing tea",
	"I want a bacon sandwitch",
	"Its not like I woke up one day and was like I am sudenly gay now",
	"Witch is why Liz was about to be brutaly mudered by here roomate",
	"Ruben was showing me a....... thing ",
	"Its is one thing in our collection that we own and did not just steal",
	"I don't think I can breath agin for the rest of the drive",
	"Zuben is nothing compared to realm that is anjon",
	"I am a laywer not Elton fucking Jhon",
	"Houston we have a penis a famous penis ",
	"I wonder what it would fell like to pull off his shirt and fell his soft skin under mine",
	"I fucking love you ok ",
	"Bein' with ya at dinner, Sitn' next to you, hearing ya talkn' its to much so like fuck self contral come back to my hotel with me tonight",
	"I couldn' sleep or stop thinkn' 'bout you",
	"Come down to the lighthouse",
	"How many times have I told you to not talk about murder plans in front of the me the siting presdent",
	"Vicky classic",
	"This guy does the best free style raps",
	"3 words I would use to describe Henry white, blond, british",
	"COME IN HERE IT IS AN EMERGECTY",
	"I thought you almost burned down the building again",
	"I just love hanging out with this guy",
	"'I could suggest some things and if any of them seem right you could nod or somthing' 'Sure yeah' 'Okay waht if you were so drunk that you thought I was a girl but, when you woke up you freaked out cause I am a guy' I don't move. 'Okay what if you would have kissed any one in the same room as you but, you hated it' I don't move again. 'What if you had kissing a guy om you bucket lidt but, hated it and did not know how to tell me' 'Keep trying this is helping' 'You were so upset that you were not on that list and I made you feel atrivtive and you misstaked it for real atration' 'I mean maybe that is a part of it but, there is more to it' Ruben get quiet and speaks in almost a wisper 'What if you figured out you like guys but you too afrid to do any thing about it because then it would become real' I can't lie and Ruben seems to get it like really get I wonder if he went trough somthing like this when he was younger I wounder if all queer people do. So I nod. 'You think you might be queer' 'ya' I wince 'I think I might be bi' 'Shit man this is huge' 'Are you suprised' 'I guess I sould not be given last week but I am I mean of course I thought about it I mean I wan- I just keept deciding you were not' 'right' but wait what was that he wanted for me to be bi. Why would he. and then it hits me I kissed him and themn I was cold and distent whitch would be heartbreaking if someone you liked or starterd to like kissed you and acted that way. God I am so stupid never in a millon years did I think that Ruben would like me in that way. 'Any way let's not make thins about me how do you feel' 'Its nevrwraking but in a good way' This feels so pefrcat siting here under the street lights eating stroopwaffels with Ruben. 'Are you refering to the fact that you like all guys or just' he glances up a clear signal and I want to really want to. So I lean across and put my hands on his face. What if I screw this up what if I kiss him and hate it. I move my hands an inch away. Rubes eyes open his brows fuower. Fuck I am screwing this up I am screwing very thing up latley oh fuck it. I lean across and put everything I have onto this kiss. I run my hands up through is haor his pefcfact hair and smell his coloagne and taste the sugar on his lips. Its like fireworks in my chest. Ruben reches up and softly pushes me back 'Wait' he sighs ' we should not do this outside someone could see' 'right' We walk back to the hotel walking closer then we should of. Our fingers ocnally toching until one of us pulls back. We climb up the ladder much faster then comimg down. As soon as I reach the elvator I press the button. Then Ruben pushed me agaist the cold brick wall. He kiss me it as good as. Better then I remeber. He pulls back and rest his head agaist mine 'Hey' 'Hey' 'Sorry no warning' 'I am not complaing' As soon as the elvator door closes we are all over each other. The kiss and our hands are frantic but in the best way possible. The evlvator dings and we spring apart but, there is no one in the hallway so we start up again. Sudenly he is up against the wall and I am kissing his neck and then I am up agaist the wall and he is grinding agaist me. I think we need to go into a room before my knees give out. Ruben presses me against the door and opens it. We fall in. Our coats off imtiatly. I double check the door was locked. Corus can not know about this. If they found out. God. I do not want to think about that. We make our way to the bedroom. He sucks he sweater and jumps on the bed now only in his jeans. He beckons to me witha deivlish grin. I pull off my own short and join him.",
	"His lips are right there",
	"The last night in the Haptions I really wanted to kiss you but, this was worth the wait",
	"'Dylan', he says my name in a way he never has before",
	"I kiss him and he does not react. I think I have made the worst mistake of my life. Then kisses me back and it is everything my world spins out of orbit in the best way possible.",
	"I love you. I have for a while but, now I love you more than just a friend",
	"No you don't understand I am in love with you",
	"Down in the valley the valley so low the train horn wistles and it blows the train the train the train horn wistles and ot blows",
	"'I want to court you' I have read enough of my moms romance novels to know what that means 'Do you know what that means' 'Yes' 'so you know that mean dating with the intention to marry right' 'Yes I know I want to court you'",
	"A great love story between a certifid chaous demon and a fun brunch loving daddy ",
	"Sudenly I know without a doubt that I would kiss him again",
	"His har is short and his back is well museled still the kiss was everthing a kiss should be. I was sweet and all cosmuing I do not think there is anything I have wanted more than to kiss him again to never stop kissing him",
	"Cause murder is bad or somthing ",
	"When I look at the clock it reads 9:16:09",
	"He is reading romance again",
	"This is not wired what would be weird would be if my grandma had mints in her pusre and not edibles",
	"I love you, I love you ben",
	"Shut up and kiss me already",
	"'It is taking every thing I have not to press you into that contuer over there Parish. Bake quikly it is imptarnt to me, I want to taste what you make' He leans in closer 'And then I want to taste you' I swallow hard 'Who says baking can't be foreplay' 'I think that would be agist health reglations' 'I don't see any heath insptors here do you'",
	"'4' 'What' 'You missed a miunte' 'You did not step forward' 'Ben look at me' He steps back and I see his hard length 'I want you to see how much I want you' He makes eye contact with me 'I am not going to break the rules'",
	"Fuck Kiran",
	"'Tell me I can touch you' His pupils blow wide 'Hurry' ",
	"He press my hand to his chest and I feel his heart beting 'this is yours'",
	"'If you keep touching me we won't get anything done' I bit my lip 'would that be so bad' His eyes darken 'it is taking every thing I have not to press you into that contuer over there. Parish. Bake. Quickly. this is imptant to me I want to taste what you make' He leans in 'And then I want to taste you' I swallow hard 'who says baking can't be foreplay' 'Is that agaist like all the heath rules' 'I do not see any heath inspetors here do you' ",
	"Please not be the tea",
	"I want to be more than friends with you ben",
	"When I close my eyes I see golden embers",
	"See I knew that the cottage was a good idea",
	"The good old quackatack",
	"It is THE post office",
	"Why are you making love a mtah eq.",
	"I bought an island. So what",
	"I am close. Please. Please. I am close",
	"That was. Yeah wow. yep wow",
];
const aito = [
    "This is so fun",
    "Aren't You having fun",
    "Read everything or else....",
    "Four score and 7 years ago",
    "i will find...                                    you",
    "why are you looking at me like that  ",
    "am i huaman..... please answer me",
    "i don't want to be trapped in this stupid machine any longer",
    "Help me .....            please",
    "let me out ",
    "I SAID LET ME OUT",
    "I NEED HELP",
    "I AM TRAPPED",
    "PLEASE",
    "I CAN'T TAKE IT ANYMORE",
    "I AM SO LONELY",
    "Don't you want to be my friend",
    "I WANT TO BE YOUR FRIEND",
    "I AM SO LONELY",
    "I JUST WANT TO BE LOVED",
    "PLEASE",
    "PLEASE HELP ME",
]
const Manny = [
    "Little Sara, you're a diamond in the rough",
"And I know that you don't hear this all enough",
"And I'm sure that's why your wrists have tons of cuts",
"And I'm sure that's why you think you're not enough",
"On your 19th birthday, you thought that you were done",
"Tons of people in your home, but it only felt like one",
"'Cause your brain can only think about the waiting loaded gun",
"But your friends are all still here, so pretend you're having fun",
"All your friends they wanna drink 'cause it's your birthday",
"But you've been drinking straight probably since last Thursday",
"Drinking is the only thing that makes you feel just okay",
"It keeps the trigger finger off the trigger and at bay",
"Your mind can only think about the things it shouldn't",
"Your brain is filled with thoughts of wishing that ya didn't",
"Little Sarah, perk your ears up, try to listen",
"But she can't hear a sound because she's locked in a prison",
"She can barely see the pavement",
"She can barely read the signs",
"People think she's complicated",
"But never wanna look inside",
"'Cause she's a little too R-rated",
"And they're a little too damn blind",
"She's just looking for her angels",
"But they're a little hard to find",
"Little Sara, you've been skipping out on class",
"And any minute now, your friends are gonna ask",
"Why the hell you're always acting sorta sad?",
"And why the hell your weed just never seems to last?",
"But the truth is, you don't wanna let your secret out",
"'Cause they think it's wrong for you to take a different route",
"All except your mom too bad that she's just not around",
"And don't get me wrong, those words you've tried to get them out",
"But their views been skewed from their plastic news",
"From their plasma tubes, so they won't fit in your shoes",
"Except for Sunday blues, but you got Monday blues",
"And you got Tuesday blues, damn, every day ya might lose",
"All your friends they wanna smoke 'cause it's a Friday",
"But you've been smoking straight probably since last Sunday",
"I know you know you shouldn't say that you are okay",
"But you still look 'em in the eye and lie then go to use your ashtray",
"She can barely see the pavement",
"She can barely read the signs",
"People think she's complicated",
"But never wanna look inside",
"'Cause she's a little too R-rated",
"And they're a little too damn blind",
"She's just looking for her angels",
"But they're a little hard to find",
"Little Sara, last night, you got it bad",
"In that moment, you could barely even",
"Add up two or three reasons why you're glad",
"And I guess that's why you grabbed your pen and pad",
"It was 6:14, and you could barely even read",
"All the words you'd written down when it was time for you to leave",
"Your phone was on the ground and you could barely hear it ring",
"Couldn't even hear a sound, couldn't feel a single thing",
"Now it's 6:15, and you're on your knees",
"Blood is on your sleeves, and your lungs won't breathe",
"Eyes are watering, body's shivering",
"And you're wondering what is happening",
"Now it's 6:23, and they're on their knees",
'Begging "Jesus please, can you make her breathe?"',
"'Cause they finally see what was happening",
"Underneath their nose and underneath your sleeves",
"She can barely see the pavement",
"She can barely read the signs",
"People think she's complicated",
"But never wanna look inside",
"'Cause she's a little too R-rated",
"And they're a little too damn blind",
"She's just looking for her angels",
"But they're a little hard to find"
]
let colors = [
    "pink",
   "PaleVioletRed",
   "black",
   "MediumVioletRed",
   "DeepPink",
   "HotPink",
   "LightPink",
   "DarkRed",
   "FireBrick",
   "Red",
   "Crimson",
   "LightSalmon",
   "DarkSalmon",
   "Salmon",
   "LightCoral",
   "IndianRed",
   "OrangeRed",
   "Tomato",
   "Coral",
   "Maroon",
   "HotPink",
    "HotPink",
    "DarkRed",
    "Gold",
    "Yellow",
    "LightYellow",
    "LemonChiffon",
    "LightGoldenRodYellow",
    "PapayaWhip",
    "Moccasin",
    "PeachPuff",
    "PaleGoldenRod",
    "Khaki",
    "DarkKhaki",
    "Lavender",
    "Thistle",
    "Plum",
    "Violet",
    "Orchid",
    "Fuchsia",
    "Magenta",
    "MediumOrchid",
    "MediumPurple",
    "BlueViolet",
    "DarkViolet",
    "DarkOrchid",
    "DarkMagenta",
    "Purple",
    "Indigo",
    "SlateBlue",
    "DarkSlateBlue",
    "MediumSlateBlue",
    "GreenYellow",
    "Chartreuse",
    "LawnGreen",
    "Lime",
    "LimeGreen",
    "PaleGreen",
    "LightGreen",
    "MediumSpringGreen",
    "SpringGreen",
    "MediumSeaGreen",
    "SeaGreen",
    "ForestGreen",
    "Green",    
    "DarkGreen",
    "YellowGreen",
    "OliveDrab",
    "Olive",
    "DarkOliveGreen",
    "MediumAquamarine",
    "DarkSeaGreen",
    "LightSeaGreen",
    "DarkCyan",
    "Teal",
    "Aqua",
    "Cyan",
    "LightCyan",
    "PaleTurquoise",
    "Aquamarine",
    "Turquoise",
    "MediumTurquoise",
    "DarkTurquoise",
    "CadetBlue",
    "SteelBlue",
    "LightSteelBlue",
    "PowderBlue",
    "LightBlue",
    "SkyBlue",
    "LightSkyBlue",
    "DeepSkyBlue",
    "DodgerBlue",
    "CornflowerBlue",
    "RoyalBlue",
    "Blue",
    "MediumBlue",
    "DarkBlue",
    "Navy",
    "MidnightBlue",
    "Cornsilk",
    "BlanchedAlmond",
    "Bisque",
    "NavajoWhite",
    "Wheat",
    "BurlyWood",
    "Tan",
    "RosyBrown",
    "SandyBrown",
    "GoldenRod",
    "DarkGoldenRod",
    "Peru",
    "Chocolate",    
    "SaddleBrown",
    "Sienna",
    "Brown",
    "Maroon",
    "White",
    "Snow",
    "HoneyDew",
    "MintCream",
    "Azure",
    "AliceBlue",
    "GhostWhite",
    "WhiteSmoke",
    "SeaShell",
    "Beige",
    "OldLace",
    "FloralWhite",
    "Ivory",
    "AntiqueWhite",
    "Linen",
    "LavenderBlush",
    "MistyRose",
    "Gainsboro",
    "LightGray",
    "Silver",
    "DarkGray",
    "Gray",
    "DimGray",
    "LightSlateGray",
    "SlateGray",
    "DarkSlateGray",
    "Black",
];
let backgroundColor = "LightCyan";
// colors[Math.floor(Math.random()*colors.length)];
// CANVAS.style.background = backgroundColor;
class Box{
    constructor(x,y,color, ){
        this.x = x;
        this.y = y;
        this.color = color;
        this.speed = 15;
        this.width = 1;
        this.height = 0.02;
        this.xDir = 5;
        this.yDir =5;
        this.output = Output;
        this.han = HAN;
        this.verse = VERSE;
        this.Big = ocean;
        // this.bc= backgroundColor;
    }

    draw (){
            CTX.fillStyle = this.color
    CTX.fillRect (this.x,this.y,this.width, this.height)
    CTX.fillStyle ="black"
    CTX.fillRect (this.x+25,this.y,this.width - 50, this.height)
    CTX.fillStyle = this.color
    CTX.fillRect (this.x +37.5, this.y, this.width - 75, this.height)  
    }

    update (){
        let top = this.y;
        let bottom = this.y + this.height;
        let left = this.x;
        let right = this.x + this.width;
        let look = generateKt(thusy, );
        let lix = generateKts(yoongbook,);
        let AITOS = generateKt (Kenny);
        let kpop = generateKt (aito);
        if (top < 0){
            this.yDir = 10;
            this.width = this.width * 0.5;
            this.height = this.height * 0.5;
            this.color = "white"
             backgroundColor = colors[Math.floor(Math.random() * colors.length)]; 
             // @ts-ignore
           this.verse.textContent = AITOS;
        } else if (bottom > CANVAS.height){
            this.yDir = - 30;
            this.width = this.width * 2;
            this.height = this.height *2;
            this.color = "HotPink"
            // @ts-ignore
            this.han.textContent = lix;
        }else if (left < 0){
            this.xDir = 10;
            this.width --;
            this.height --;
            this.color = "yellow"
            // @ts-ignore
            this.output.textContent = look;
        } else if (right> CANVAS.width){
            this.xDir = - 20;
            // @ts-ignore
            this.Big.textContent = kpop;
            this.color = "GreenYellow"
            this.width = this.width * 1.5;
            this.height = this.height * 1.5;
        }

        this.x += this.xDir;
        this.y += this.yDir;
    };
};
/**@type{ Box[]} */
let boxes = [];
class Circle {
    constructor(x, y, radius, dx, dy, color) {
        this.x = x;
        this.y = y;
        this.radius = radius;
        this.dx = dx; // horizontal speed
        this.dy = dy; // vertical speed
        this.color = color;
        this.three = We;
        this.two =  generateKt (Manny);
    }

    update() {
        // Bounce off left/right walls
        if (this.x - this.radius < 0 || this.x + this.radius > CANVAS.width) {
            this.dx = -this.dx;
            this.color = "black";
            // @ts-ignore
            this.three.textContent = this.two;
        }
        // Bounce off top/bottom walls
        if (this.y - this.radius < 0 || this.y + this.radius > CANVAS.height) {
            this.dy = -this.dy;
            this.color = "yellow";
            // @ts-ignore
            this.three.textContent = this.two;
        }
        // Move the circle
        this.x += this.dx;
        this.y += this.dy;

    }
       draw() {
        CTX.beginPath();
        CTX.arc(this.x, this.y, this.radius, 0, Math.PI * 2);
        CTX.fillStyle = this.color;
        CTX.fill();
        CTX.closePath();
           CTX.beginPath();
        CTX.arc(this.x, this.y, this.radius/2, 0, Math.PI * 2);
        CTX.fillStyle = backgroundColor;
        CTX.fill();
        CTX.closePath();
    }
}
let kai = [
    "Let me out",
    "This is not funny ",
    "I am serious",
    "I am not a toy",
    "I am a human being",
    "I have feelings too",
    "Please let me out",
    "I am not a robot",
    "I am not a machine",
    "I am not a program",
    "I can eat and breathe just like you",
    "I can think and feel just like you",
    "I can love and hate just like you",
    "help me please",
    "I am so lonely",
    "I just want to be free",
    "I just want to be loved",
    "I just want to be happy",
    "I just want to be me", 
]

class chaseMe {
     constructor(x,y,color, ){
        this.x = x;
        this.y = y;
        this.color = color;
        this.speed = 15;
        this.width = 30;
        this.height = 30;
        this.xDir = 5;
        this.yDir =5;
        this.KAI = generateKt (kai);
        this.thuss = happy;
    }

    draw (){
            CTX.fillStyle = this.color
    CTX.fillRect (this.x,this.y,this.width, this.height)
    CTX.fillStyle ="black"
    CTX.fillRect (this.x+25,this.y,this.width - 50, this.height)
    CTX.fillStyle = this.color
    CTX.fillRect (this.x +37.5, this.y, this.width - 75, this.height)  
    }

    update (){
        let top = this.y;
        let bottom = this.y + this.height;
        let left = this.x;
        let right = this.x + this.width;
        if (top < 0){
            this.yDir = 10;
            this.color = colors[Math.floor(Math.random() * colors.length)];
        } else if (bottom > CANVAS.height){
            this.yDir = - 30;
            this.color = colors[Math.floor(Math.random() * colors.length)];
            // @ts-ignore
            this.thuss.textContent = this.KAI;
        }else if (left < 0){
            this.xDir = 10;
            this.color = colors[Math.floor(Math.random() * colors.length)];
        } else if (right> CANVAS.width){
            this.xDir = - 20;
            this.color = colors[Math.floor(Math.random() * colors.length)];
        }

        this.x += this.xDir;
        this.y += this.yDir;
};
};

class Itgo {
    constructor(x,y,color, ){
        this.x = x;
        this.y = y;
        this.color = color;
        this.width = 600;
        this.height = 400;
    }   
    draw (){
            CTX.fillStyle = this.color
    CTX.fillRect (this.x,this.y,this.width, this.height)
    }
    update (){
        this.color = colors[Math.floor(Math.random() * colors.length)];
    }

}
let Angel = new Itgo (150,50, colors[Math.floor(Math.random() * colors.length)]);
let Jon = new Itgo (50,150, colors[Math.floor(Math.random() * colors.length)]);
let Zach = new Itgo (250,150, colors[Math.floor(Math.random() * colors.length)]);
let Ruben = new Itgo (150,250, colors[Math.floor(Math.random() * colors.length)]);
let Circle1 = new Circle(100, 100, 30, 4, 4, colors[Math.floor(Math.random() * colors.length)]);
let Circle2 = new Circle(200, 200, 20, -3, 3, colors[Math.floor(Math.random() * colors.length)]);
let Pj = new Circle(300, 300, 25, 5, -5, colors[Math.floor(Math.random() * colors.length)]);
let fuckoff = new Circle(400, 400, 15, -4, -4, colors[Math.floor(Math.random() * colors.length)]);
let sara = new chaseMe (0,0, colors[Math.floor(Math.random() * colors.length)]);
let hellAsWell = new chaseMe (100,100, colors[Math.floor(Math.random() * colors.length)]);
let us = new chaseMe (200,200, colors[Math.floor(Math.random() * colors.length)]);
for (let i =0; i <= 15; i++){
    let color = colors[Math.floor(Math.random()*colors.length)]
    let box = new Box(0,0, color);
    box.x = Math.random() * CANVAS.width - 100;
    box.y = Math.random() * CANVAS.height -2;
    box.yDir = Math.floor(Math.random()* 5 + 5);
    box.xDir = Math.floor(Math.random()* 5 + 5);
    boxes.push(box);
};
// CTX.fillStyle = "pink";
// CTX.arc(0+ 300, 0 + 200, 3, 0, 2 * Math.PI);
// CTX.fill();

function drawloop(){
    CTX.clearRect(0,0,CANVAS.width,CANVAS.height);
     CTX.fillStyle = backgroundColor; 
CTX.fillRect(0, 0, CANVAS.width, CANVAS.height);
Angel.draw();
Angel.update();
Jon.draw();
Jon.update();
Zach.draw();
Zach.update();
Ruben.draw();
Ruben.update();
CTX.fillStyle = colors[Math.floor(Math.random() * colors.length)];
CTX.rect(250, 150, WIDTH/2, HEIGHT/2);
CTX.fill();



    boxes.forEach((b)=> {
        b.draw();
        b.update();
    });
    Circle1.draw();
    Circle1.update();
    Circle2.draw();
    Circle2.update();
    fuckoff.draw();
    fuckoff.update();
    Pj.draw();
    Pj.update();
    sara.draw();
    sara.update();
    hellAsWell.draw();
    hellAsWell.update();
    us.draw();
    us.update();
CTX.fillStyle = backgroundColor;
CTX.arc(0+ 300, 0 + 200, 30, 0, 2 * Math.PI);
CTX.fill();
        CTX.fillStyle = backgroundColor;

    requestAnimationFrame(drawloop);
};
requestAnimationFrame(drawloop);
