//@ts-check

/** @type { HTMLCanvasElement } */
//@ts-ignore This is an HTML Canvas
const CANVAS = document.getElementById("game-canvas");
/**@type {CanvasRenderingContext2D} */
//@ts-ignore
const CTX = CANVAS.getContext("2d");
const Output = document.getElementById("names");
const HEIGHT = 500;
const WIDTH = 890;
CANVAS.height = HEIGHT;
CANVAS.width = WIDTH;
const getRandomIndexs = function (a) {
    let rand = Math.random() * a.length;
    return Math.floor(rand);
};
let getRandomWords = function (a) {
    return a[getRandomIndexs(a)];
};
const generateKt = function (a, ){
    let mk =
        getRandomWords (a) +
    ""
    return mk;
};
const thusy = [
    "Hellevator - Stray Kids",
    "Double Knot - Stray Kids",
    "Mixtape: Gone Days - Stray Kids",
    "Double Knot (English ver.) - Stray Kids",
    "My Pace (Japanese Ver.) - Stray Kids",
    "Double Knot (Japanese Ver.) - Stray Kids",
    "Levanter (Japanese Ver.) - Stray Kids",
    "Mixtape: On Track - Stray Kids",
    "TOP (Japanese Ver.) - Stray Kids",
    "SLUMP (Japanese Ver.) - Stray Kids",
    "TOP  Stray Kids",
    "TOP (English Ver.) - Stray Kids",
    "Hello Stabger - Stray Kids",
    "Back Door (Japanese Ver.) - Stray Kids",
    "ALL IN (Korean Ver.) - Stray Kids",
    "Going Dumb (with Stray Kids) - Alesso, Stray Kids, Corsak",
    "Mixtape: OH - Stray Kids",
    "Scars - Stray Kids",
    "CALL - Stray Kids",
    "Christmas EveL - Stray Kids",
    "24 to 25 - Stray Kids",
    "Winter Falls - Stray Kids",
    "DOMINO (English Ver.) - Stray Kids",
    "MANIAC (Japanese Ver.) - Stray Kids",
    "Your Eyes - Stray Kids",
    "CIRCUS - Stray Kids",
    "Fairytale - Stray Kids",
    "VENOM (Japanese Ver.) - Stray Kids",
    "Silent Cry (Japanese Ver.) - Stray Kids",
    "Mixtape: Time Out - Stray Kids",
    "CASE 143 (Japanese Ver.) - Stray Kids",
    "THE SOUND - Stray Kids",
    "There - Stray Kids",
    "Like Magic  - Stray Kids, J.Y.Park, ITZY, NMIXX",
    "SUper Bowl (Japanese Ver.) - Stray Kids",
    "Social Path - Stray Kids, LiSA",
    "Butterflies - Stray Kids",
    "All My Life (Stray Kids Remix) - Stray Kids, Lil Durk",
    "WHY? - Stray Kids",
    "lose My Breath (Feat. Charlie Puth) - Stray Kids, Charlie Puth",
    "Chk Chk Boom - Stray Kids",
    "SLASH (From 'DeadPool & Wolverine' - Stray Kids",
    "NIGHT - Stray Kids",
    "Falling Up (English Ver.) - Stray Kids",
    "Falling Up - Stray Kids",
    "Come Play (from the series Arcane League of Legends) - Stray Kids,etc.",
    "Walkin' On Water - Stray Kids",
    "GIANT (Korean Ver.) - Stray Kids",
    "Burnin' Tiers (Changbin & I.N) - Stray Kids",
    "Trunman (Han & Felix) - Stray Kids",
    "ESCAPE (Bang Chan & Hyunjin) - Stray Kids",
    "CIMEMA (Lee Know & Seungmin) - Stray Kids",
    "Hollow - Stray Kids",
    "Parade - Stray Kids",
    "Never Alone - Stray Kids",
    "just a little - Stray Kids",
    "CERMONY  - Stray Kids",
    "CERMONY (KARMA Ver.) - Stray Kids",
    "BEWARE - Stray Kids",
    "Spread My Wings - Stray Kids",
    "YAYAYA - Stray Kids",
    "District 9 - Stray Kids",
    "Mirror - Stray Kids",
    "Grow Up - Stray Kids",
    "My Pace - Stray Kids",
    "Voices - Stray Kids",
    "Question - Stray Kids",
    "M.I.A. - Stray Kids",
    "AWkward Silence - Stray Kids",
    "I am YOU - Stray Kids",
    "Get Cool - Stray Kids",
    "MIROH - Stray Kids",
    "Boxer - Stray Kids",
    "Chronosaurus - Stray Kids",
    "19 - Stray Kids",
    "Side Effects - Stray Kids",
    "TMT - Stray Kids",
    "Double Knot - Stray Kids",
    "Levanter - Stray Kids",
    "Astronaut - Stray Kids",
    "GLOW - Stray Kids",
    "School Life - Stray Kids",
    "4419 - Stray Kids",
    "NOT! - Stray Kids",
    "Awaken - Stray Kids",
    "ROCK - Stray Kids",
    "Grow UP - Stray Kids",
    "3rd Eye - Stray Kids",
    "WHO? - Stray Kids",
    "My Pace - Stray Kids",
    "Vocies - Stray Kids",
    "YOU. - Stray Kids",
    "My Side - Stray Kids",
    "Hero's Soup - Stray Kids",
    "N/S - Stray Kids",
    "0325 - Stray Kids",
    "Entrance - Stray Kids",
    "Victory Song - Stray Kids",
    "Maze of Memories - Stray Kids",
    "Road Not Taken - Stray Kids",
    "Side Effects - Stray Kids",
    "TMT - Stray Kids",
    "Mixtape#1 - Stray Kids",
    "Mixtape#2 - Stray Kids",
    "Mixtape#3 - Stray Kids",
    "Mixtape#4 - Stray Kids",
    "STOP - Stray Kids",
    "Double Knot - Stray Kids",
    "Booster - Stray Kids",
    "Sunshine - Stray Kids",
    "You Can STAY - Stray Kids",
    "GO LIVE - Stray Kids",
    "God's Menu - Stray Kids",
    "Easy - Stray Kids",
    "Pacemaker - Stray Kids",
    "Airplane - Stray Kids",
    "Another Day - Stray Kids",
    "Phobia - Stray Kids",
    "Blue Print - Stray Kids",
    "TA - Stray Kids",
    "Haven - Stray Kids",
    "The Tortosie and the Hare - Stray Kids",
    "Back Door - Stray Kids",
    "B Me - Stray Kids",
    "Any - Stray Kids",
    "Ex - Stray Kids",
    "We Go (Bang Chan, Changbin, HAN) - Stray Kids",
    "Wow (Lee Know, Hyunjin, Felix) - Stray Kids",
    "My Universe - Stray Kids",
    "Easy - Stray Kids",
    "ALL IN - Stray Kids",
    "One Day - Stray Kids",
    "CHEESE - Stray Kids",
    "Thunderous - Stray Kids",
    "DOMINO - Stray Kids",
    "SSKICK - Stray Kids",
    "The Veiw - Stray Kids",
    "Sorry, I Love You - Stray Kids",
    "Silent Cry - Stray Kids",
    "Secret Secret - Stray Kids",
    "Star Lost - Stray Kids",
    "Red Lights (Bang Chan, Hyunjin) - Stray Kids",
    "Surfin' (Lee Know, Changbin, Felix) - Stray Kids",
    "Gone Away (HAN, Seungmin , I.N) - Stray Kids",
    "WOLFGANG - Stray Kids",
    "Awaken - Stray Kids",
    "ROCK - Stray Kids",
    "3rd Eye - Stray Kids",
    "Placebo - Stray Kids",
    "Insomnia - Stray Kids",
    "Behind the Light - Stray Kids",
    "My Side - Stray Kids",
    "0325 - Stray Kids",
    "For You - Stray Kids",
    "Maze of Memories - Stray Kids",
    "Broken Compass - Stray Kids",
    "Hoodie Season - Stray Kids",
    "VENOM - Stray Kids",
    "MANIAC - Stray Kids",
    "Charmer - Stray Kids",
    "FREEZE - Stray Kids",
    "Lonley St. - Stray Kids",
    "Waiting For Us (Bang Chan, Lee Know, Seungmin, I.N) - Stray Kids",
    "Muddy Water (Changbin, Hyunjin, HAN, Felix) - Stray Kids",
    "CASE 143 - Stray Kids",
    "CHILL - Stray Kids",
    "Give Me Your TMI - Stray Kids",
    "SUPER BOARD - Stray Kids",
    "3RACHA (Bang Chan, Changbin, HAN)",
    "TASTE (Lee Know, Hyunjin, Felix) - Stray Kids",
    "Can't Stop (Seungmin, I.N) - Stray Kids",
    "CIRCUS (Korean Ver.) - Stray Kids",
    "FAM (Korean Ver.) - Stray Kids",
    "Connected (Bang Chan) - Stray Kids",
    "Limbo (Lee Know) - Stray Kids",
    "DOODLE (Changbin) - Stray Kids",
    "Love Untold (Hyunjin) - Stray Kids",
    "RUN (HAN) - Stray Kids",
    "Deep End (Felix) - Stray Kids",
    "Stars and Raindrops (Seungmin) - Stray Kids",
    "Hug Me (I.N) - Stray Kids",
    "ZONE (Bang Chan, Changbin, HAN) - Stray Kids",
    "Close (HAN) - Stray Kids",
    "Streetkight (Changbin) - Stray Kids",
    "i hate to admit (Bang Chan) - Stray Kids",
    "I GOT IT (HAN) - Stray Kids",
    "miss you (Hyunjin) - Stray Kids",
    "Maknae On Top (I.N) - Stray Kids",
    "Alien (HAN) - Stray Kids",
    "Because (Changbin, Felix) - Stray Kids",
    "Peice of a Puzzle (Changbin, Seungmin) - Stray Kids",
    "Wish You Back (HAN) - Stray Kids",
    "HaPpy (HAN) - Stray Kids",
    "Up All Night (Bang Chan, Changbin, Felix, Seungmin) - Stray Kids",
    "Drive (Bang Chan, Lee Know) - Stray Kids",
    "ice.cream (Hyunjin) - Stray Kids",
    "THE SOUND - Stray Kids",
    "Battle Ground - Stray Kids",
    "Lost Me - Stray Kids",
    "DLMLU - Stray Kids",
    "Novel - Stray Kids",
    "Scars - Stray Kids",
    "There - Stray Kids",
    "Hall of Fame - Stray Kids",
    "S-Class - Stray Kids",
    "ITEM - Stray Kids",
    "Super Bowl - Stray Kids",
    "TOPLINE (Feat. Tiger JK) - Stray Kids, Tiger JK",
    "DLC - Stray Kids",
    "GET LIT - Stray Kids",
    "Collision - Stray Kids",
    "FNF - Stray Kids",
    "Youtiful - Stray Kids",
    "THE SOUDN (Korean Ver.) - Stray Kids",
    "Mixtape:Tiem Out - Stray Kids",
    "MEGAVERSE - Stray Kids",
    "LALALALA - Stray Kids",
    "BLIND SPOT - Stray Kids",
    "COMFLEX - Stray Kids",
    "Cover Me - Stray Kids",
    "Leave - Stray Kids",
    "MOUNTAINS - Stray Kids",
    "JJAM - Stray Kids",
    "I Like It - Stray Kids",
    "Runners - Stray Kids",
    "twilight - Stray Kids",
    "GIANT - Stray Kids",
    "NIGHT - Stray Kids",
    "Saiyan - Stray Kids",
    "Christmas Love - Stray Kids",
    "NIGHT (English Ver.) - Stray Kids",
    "Walkin' On Water - Stray Kids",
    "Bounce Back - Stray Kids",
    "U (Feat. TABLO) - Stray Kids, TABLO",
    "Railway (Bang Chan) - Stray Kids",
    "Unfair (Felix) - Stray Kids",
    "HALLUCINATION (I.N) - Stray Kids",
    "Youth (Lee Know) - Stray Kids",
    "So Good (Hyunjin) - Stray Kids",
    "ULTRA - Stray Kids",
    "Hold my Hand (HAN) - Stray Kids",
    "As we are (Seungmin) - Stray Kids",
    "BLEEP - Stray Kids",
    "CEREMONY - Stray Kids",
    "CREED - Stray Kids",
    "MESS - Stray Kids",
    "In My Head - Stray Kids",
    "Half Time - Stray Kids",
    "Phoneix - Stray Kids",
    "Ghost - Stray Kids",
    "0801 - Stray Kids",
    "Blue Orangeade - Tomorrow x Together",
    "CROWN - Tomorrow x Together",
    "Our Summer - Tomorrow x Together",
    "Cat & Dog - Tomorrow x Together",
    "Nap of a star - Tomorrow x Together",
    "Cat & Dog (English Ver.) - Tomorrow x Together",
    "Our Summer (Acousitic Ver.) - Tomorrow x Together",
    "Anegl Or Devil (Japanese Ver.) - Tomorrow x Together",
    "Drama - Tomorrow x Together",
    "Can't You See Me? - Tomorrow x Together",
    "Fairy of Shamppoo - Tomorrow x Together",
    "Maze in the Mirror - Tomorrow x Together",
    "PUMA - Tomorrow x Together",
    "Eternally - Tomorrow x Together",
    "Drama (Japanese Ver.) - Tomorrow x Together",
    "Ghosting - Tomorrow x Together",
    "Blue Hour - Tomorrow x Together",
    "We Lost The Summer - Tomorrow x Together",
    "Wishlist - Tomorrow x Together",
    "Way Home - Tomorrow x Together",
    "Your Light - Tomorrow x Together",
    "Your Light (Japanese Ver.) - Tomorrow x Together",
    "Your LIght (Instrumental) - Tomorrow x Together",
    "Force - Tomorrow x Together",
    "Love Sight - Tomorrow x Together",
    "Love Sight (Instrumental) - Tomorrow x Together",
    "OX1=LOVESONG(I Know I Love You) feat. pH-1, Woodie Gochild, Seori - Tomorrow x Together",
    "OX1=LOVESONG(I Know I Love You) feat. MOD SUN - Tomorrow x Together",
    "Ito - Tomorrow x Together",
    "EYES (from 'Aemored Saurus') - Tomorrow x Together",
    "OX1=LOVESONG (I Know I Love You) Japanese Ver. - Tomorrow x Together",
    "Ito - Tomorrow x Together",
    "MOA Diary (Dubaddu Wari Wari) Japanese Ver.  - Tomorrow x Together",
    "Magic - Tomorrow x Together",
    "Opening Sequence - Tomorrow x Together",
    "Good Boy Gone Bad - Tomorrow x Together",
    "Trust Fund Baby - Tomorrow x Together",
    "Lonley Boy (The tattoo on my ring finger) - Tomorrow x Together",
    "Thursday's Child Has Far To Go - Tomorrow x Together",
    "Valley of Lies - Tomorrow x Together",
    "Good Boy Gone Bad (Japanese Ver.) - Tomorrow x Together",
    "Free Falling - Tomorrow x Together",
    "Devil by the Window - Tomorrow x Together",
    "Sugar Rush Ride - Tomorrow x Together",
    "Happy Fools (feat. Coi Leray) - Tomorrow x Together, Coi Leray",
    "Tinnitus (Wanna be a Rock) - Tomorrow x Together",
    "Farewell, Neverland - Tomorrow x Together",
    "Goodbye Now - Tomorrow x Together",
    "Goodbye Now (Instrumental) - Tomorrow x Together",
    "Sugar Rush Ride (Japanese Ver.) - Tomorrow x Together",
    "Do It Like That  - Tomorrow x Together",
    "Do It Like That (Jersey Club Remix) - Tomorrow x Together",
    "Do It Like That (Pop R&B Remix) - Tomorrow x Together",
    "Do It Like That (Alan Walker Remix) - Tomorrow x Together",
    "Do It Like That (Jax Jones Remix) - Tomorrow x Together",
    "Back For More (with Anitta) - Tomorrow x Together, Anitta",
    "Back For More (TXT Ver.) - Tomorrow x Together, Anitta",
    "Deja Vu (Japanese Ver.) - Tomorrow x Together",
    "Open Always Wins - Tomorrow x Together",
    "Heaven - Tomorrow x Together",
    "Over the Moon - Tomorrow x Together",
    "Danger - Tomorrow x Together",
    "Resist (Not Gonna Run Away) - Tomorrow x Together",
    "Forty One Winks - Tomorrow x Together",
    "Higer Than Heaven - Tomorrow x Together",
    "Love Story - Tomorrow x Together",
    "Rise - Tomorrow x Together",
    "Love Language - Tomorrow x Together",
    "When Day Comes - Tomorrow x Together",
    "Step By Step - Tomorrow x Together",
    "butterflies (feat. TAEHUN & Kim Chaewon of LE SSERAFIM) - Tomorrow x Together, JVKE, LE SSERAFIM, TAEHUN, KIM CHAEWON",
    "New Rules - Tomorrow x Together",
    "9 and Three Quarters (Run Away) - Tomorrow x Together",
    "Roller Coaster - Tomorrow x Together",
    "Poppin' Stars - Tomorrow x Together",
    "Can't We Just Leave The Monster Alive - Tomorrow x Together",
    "Magic Island - Tomorrow x Together",
    "20cm - Tomorrow x Together",
    "Angel Or Devil - Tomorrow x Together",
    "Intro: DREAMING - Tomorrow x Together",
    "Force - Tomorrow x Together",
    "Outro: STILL - Tomorrow x Together",
    "Anti-Romantic - Tomorrow x Together",
    'OX1=LOVESONG (I Know I Love YOU) feat. Seori - Tomorrow x Together, Seori',
    "Magic - Tomorrow x Together",
    "Ice Cream - Tomorrow x Together",
    "What if I had been that PUMA - Tomorrow x Together",
    "No Rules - Tomorrow x Together",
    "Dear Sputnik - Tomorrow x Together",
    "Frost - Tomorrow x Together",
    "Lo$er=L<3ver - Tomorrow x Together",
    "Intro: FLOATING- Tomorrow x Together",
    "Outro: FALLING - Tomorrow x Together",
    "Growing Pain- Tomorrow x Together",
    "Chasing That Feeling - Tomorrow x Together",
    "Back For More (TXT Ver.) - Tomorrow x Together",
    "Dreamer - Tomorrow x Together",
    "Happily Ever After - Tomorrow x Together",
    "Skipping Stones - Tomorrow x Together",
    "Blue Spring - Tomorrow x Together",
    "Do It Like That - Tomorrow x Together",
    "I'll See You There Tomorrow - Tomorrow x Together",
    "- --- -- ---.-.-.---.-- - Tomorrow x Together",
    "Deja Vu - Tomorrow x Together",
    "Miracle - Tomorrow x Together",
    "The Killa (I Belong to You) - Tomorrow x Together",
    "Quarter Life - Tomorrow x Together",
    "Upside Down Kiss  - Tomorrow x Together",
    "Beautiful Strangers - Tomorrow x Together",
    "Ghost Girl - Tomorrow x Together",
    "Sunday Driver - Tomorrow x Together",
    "Dance With You - Tomorrow x Together",
    "Take My Half - Tomorrow x Together",
    "Bird Of Night - Tomorrow x Together",
    "Song Of Stars - Tomorrow x Together",
    "Beautiful Staranger (Japansese Ver.) - Tomorrow x Together",
    "Sara - We Three",
    "Hell As Well - We Three",
    "If I Loved a Boy - We Three",
    "Secrets - We Three",
    "Daydreams - We Three",
    "Exes Flowers - We Three",
    "In Therapy - We Three",
    "Bad Ass Bitch - We Three",
    "Body Fat Percentage - We Three",
    "HALF HEARTED - We Three",
    "She's Got That  - We Three",
    "Same Way Too - We Three",
    "Lifeline - We Three",
    "Heaven's Not Too Far - We Three",
    "Six Feet Deep - We Three",
    "i wanna love somebody - We Three",
    "30,000 ft - We Three",
    "Confident - We Three",
    "Bad Guy - We Three",
    "3 Am - We Three",
    "Superman - We Three",
    "You and I - We Three",
    "Machine - We Three",
    "hold me, baby - We Three",
    "So They Say - We Three",
    "Fall For You - We Three",
    "Insomniac - We Three",
    "Nothing Else Matters - We Three",
    "Kissin' When We're Mad - We Three",
    "Fairytale - We Three",
    "Running - We Three",
    "Fire Away - We Three",
    "Our Last Christmas Eve - We Three",
    "Testify - We Three",
    "Makeup - We Three",
    "Dancing In The Dark - We Three",
    "Full Time Job - We Three",
    "Hold On - We Three",
    "You Space and Time - We Three",
    "Nightlight - We Three",
    "Sweater Weather - We Three",
    "Timeless - We Three",
    "Stuck Like This - We Three",
    "Dear PARANOIA - We Three",
    "mid July - We Three",
    "when i'm with you - We Three",
    "couch - We Three",
    "Us - We Three",
    "insecure - We Three",
    "Chase Me - We Three",
    "OVERDOSE - We Three",
    "Broke in two - We Three",
    "Sincerly, ME - We Three",
    "Body Fat Percentage - We Three",
    "If I Saw You - We Three",
    "Happy - We Three",
    "Full Time Job - We Three",
    "Bad at Love - We Three",
    "Love Me In A Circle - We Three",
    "When I'm with You - We Three, Noah Guthrie",
    "Paradise - We Three",
    "Full Tiem Job (Live) - We Three",
    "Bas ass Bitch (Live) - We Three",
    "Same Way Too (Live) - We Three",
    "She's Got That (Live) - We Three",
    "Bad Guy (Live) - We Three",
    "Daydreams (Live) - We Three",
    "You Space And Time (Live) - We Three",
    "Heaven's Not Too Far (Live) - We Three",
    "Lifeline (Live) - We Three",
    "Half Hearted (Live) - We Three",
    "Insomnic (Live) - We Three",
    "3AM / Overdose (Live) - We Three",
    "Sara (Live)  - We Three",
    "I Wanna Love Somebody (Live) - We Three",
    "Kissin' When We're Mad (Live) - We Three",
    "Somebody Once Told Me (Live) - We Three",
    "God Things  - We Three",
    "50 Shades of Pink - We Three",
    "i wrote this song in your lap - We Three",
    "Glow - Big Ocean",
    "BLOW- Big Ocean",
    "SLOW (Feat. Young K (Day 6))- Big Ocean, Young K",
    "brighT- Big Ocean",
    "SINKING- Big Ocean",
    "FADE OUT- Big Ocean",
    "ATTENTION- Big Ocean",
    "END OF TIME- Big Ocean",
    "BUCKET HAT- Big Ocean",
    "Multiverse - 1verse",
    "Shatterd (ENG ver.)- 1verse",
    "Shatterd (KOE ver.) - 1verse",
    "Here's Your Love Song - TX2, Chase Elliot, Mantra Beats",
    "Living Punk Rock - TX2",
    "Harpoon - TX2",
    "Not Me - TX2",
    "No Place Like Home - TX2",
    "Nail In The Coffin - TX2",
    "Step Over A Body - TX2",
    "Vampire By Rumor - TX2",
    "Fuck It All - TX2",
    "Thank You For... - TX2",
    "TRUST NO ONE - TX2",
    "Drop Dead - TX2",
    "Where'd U Come From - TX2",
    "Pull The Plug - TX2",
    "Heaven Was Full(I'm Headed Straight To Hell) - TX2",
    "A Choice - TX2",
    "Flowers - TX2",
    "Two Pills - TX2",
    "I Would Hate Me Too - TX2",
    "Randy McNally(No Love Like Christan Hate) - TX2",
    "Say You're Insercure (Without Saying It) - TX2",
    "Loaded Guns - TX2",
    "The Witching Hour - TX2",
    "Antidote - TX2",
    "Animal - TX2",
    "Walking Dead Man - TX2",
    "Sex Sells (Hard) - TX2",
    "Degrade Me - TX2",
    "Black Weeding - TX2",
    "Am I A Ghost - TX2",
    "6 Seconds Left - TX2",
    "Burn - TX2",
    "So Numb - TX2",
    "Vendetta (feat. Johnny 3 Tears) - TX2, Johnny 3 Tears",
    "Hatchet - TX2",
    "Swing At Me - TX2",
    "MAD (Feat. Ice Nine Kills) - TX2, Ice Nine Kills",
    "Swing At Me - TX2",
    "THIS ISN'T ABOUT DRUGS (I SWEAR) Feat. From First To Last - TX2",
    "Cruel World - TX2",
    "Violent Nature - TX2",
    "Cry - TX2, Hopelessly Devoted To You",
    "Infamous - TX2",
    "HOSTAGE (they will not erase us) - TX2",
    "Hollow Frame - TX2",
    "Feed (feat. DeathbyRomy) - TX2, DeathbyRomy",
    "Nice Guy (feat. Ekoh) - TX2, Ekoh",
    "run it up - bbno$, slightbeats",
    "damn - bbno$, Lzr",
    "lets go - bbno$",
    "thots - bbno$, MIA GLADSTONE, Cig.Margot",
    "mmmyea - bbno$, Trippy tha Kid",
    "lit like candle - bbno$, nowill",
    "Pay Attention - bbno$",
    "bandaid - bbno$",
    "how i do - bbno$, Cig.Margot, Al Rocco",
    "run this shit - bbno$, Yung Gray, downtime",
    "benihana (ft. yung gravy prod.sonn) - bbno$, yung gravy, prod.sonn",
    "Boomin - bbno$, yung gravy",
    "zoom - bbno$, hollow",
    "wonkybish - bbno$, Trippy tha Kid, Senojnayr",
    "scooter - bbno$, Lzr, AKAY",
    "Whippin - bbno$, yung gravy",
    "ferrari fitness - bbno$, Futon, lentra",
    "dunkaroos - bbno$, Lzr",
    "what hook? - bbno$, Trippy tha Kid, howl",
    "lickity split - bbno$, Trippy tha Kid, hollow",
    "coasting - bbno$, hollow, Futon",
    "politics - bbno$, Creepa, Trippy tha Kid",
    "Rosisserie - bbno$, yung gravy",
    "Gasoline (feat. Young King Dave) - bbno$, yung gravy, Young King Dave",
    "Gold (feat. Mia Gladstone) - bbno$, yung gravy",
    "Whippin - bbno$, yung gravy",
    "Boomin - bbno$, yung gravy",
    "skrrrr - bbno$, Max Wellls, Cig.Margot, Lzr",
    "ploy - bbno$",
    "what i do - bbno$, Yung bambi, lentra",
    "who dat boi - bbno$, lentra, So Loki",
    "I - bbno$",
    "semi auto - bbno$, Hounds, Trippy tha Kid",
    "What a Day! - bbno$, funton Don",
    "Too Much Yello - bbno$, ROSHIMA",
    "super saiyan flex - bbno$, Al Rocco, yung castor, 8mc",
    "3mo - bbno$, lentra",
    "litmas - bbno$, Lzr",
    "golden rule - bbno$, downtime",
    "drip - bbno$, jellorio",
    "moneytalk - bbno$, Julez",
    "WYWD - bbno$, Julez",
    "lavish - bbno$, hollow",
    "tony thot - bbno$, lentra",
    "too easy - bbno$, downtime",
    "tokyo glo remix - bbno$, Raka, LMC",
    "moves - bbno$, lentra",
    "fragile - bbno$, So Loki",
    "bubblin - bbno$, So Loki",
    "swagu - bbno$, So Loki",
    "more concrete - bbno$, So Loki",
    "okay - bbno$, So Loki",
    "checkmate - bbno$, So Loki",
    "money conversation - bbno$, Y2K",
    "Mr.Miyagi - bbno$, andrei, Waka Flocka Flame",
    "thankful - bbno$, Y2K, Lewis Grant",
    "jurassic - bbno$, lentra, TrippyThaKid",
    "doubles - bbno$, Swerzie, Downtime",
    "shinning - bbno$, lentra",
    "With Ease - bbno$, Billy Marchiafava, ANH",
    "hyrule temple - bbno$, DJ Yung Vamp",
    "sriracha - bbno$, lentra",
    "pouch - bbno$, Y2K",
    "cheesy - bbno$, Warhol.SS, Dilip",
    "Bad Boy - bbno$, Yung Bae, Billy Marchiafava",
    "Lalala - bbno$, Y2K",
    "slop - bbno$",
    "Lalala (Polyphina Remix) - bbno$, Y2K, Polyphina",
    "Lalala (Oliver Heldens Remix) - bbno$, Y2K, Oliver Heldens",
    "Lalala (IIkan Gunuc Remix) - bbno$, Y2K, IIkan Gunuc",
    "Lalala (Remic - [feat. Enrique Iglesias & Carly Rae Jepson]) - bbno$, Y2K, Enrique Iglesias, Carley Rae Japson",
    "shinning on my ex - bbno$, Yung Gravy",
    "iunno - bbno$, BABY GRAVY, Yung Gravy",
    "Welcome to Chilis - bbno$, BABY GRAVY, Yung Gravy",
    "Off The Goop - bbno$, BABY GRAVY, Yung Gravy, Cuco",
    "out of control - bbno$, ceo@business.net, lentra",
    "Diva Bonita - bbno$, SwuM",
    "Viscaity - bbno$, SwuM",
    "Lamb Kabob - bbno$, SwuM",
    "Voodo - bbno$, SwuM",
    "Big Racks - bbno$, SwuM",
    "mememe - bbno$, lentra",
    "quarantine freestyle - bbno$, lentra",
    "what would baby do? - bbno$, lentra",
    "astrology - bbno$, lentra",
    "jack money bean - bbno$, Yung Gravy, lentra",
    "imma - bbno$, lentra",
    "backwards - bbno$, lentra",
    "Wawawa - bbno$, Y2K",
    "help herself - bbno$, Diamond Pistols",
    "bad to the bone - bbno$. lentra",
    "sorry - bbno$",
    "my oh my - bbno$",
    "wussup - bbno$, Yung Gravy",
    "edamame - bbno$, Rich Brown",
    "take a trip - bbno$, ceo@business.net, jungle bobby, lentra",
    "i remember - bbno$",
    "yoga - bbno$, Rebecca Black",
    "brainless - bbno$, lentra",
    "big boss baby - bbno$, lentra",
    "mathematics - bbno$",
    "piccolo - bbno$",
    "pogo - bbno$, Diplo",
    "sophisticated - bbno$",
    "C'est La Vie (with bbno$ & Rich Brian) - bbno$, Yung Gravy, Rich Brian",
    "top gun - bbno$",
    "i see london i see france - bbno$",
    "help herself (dnb remix) ~ spotify singles - bbno$",
    "feel good inc (bbno$ re-finessed) ~ spotify singles - bbno$",
    "still - bbno$",
    "Not A Beanie - bbno$, Connor Price",
    "Ushme Uturbe - bbno$, Kalush Orchestra, DITVAK, KALUSH",
    "Goodness Graciuos - bbno$, BABY GRAVY, Yung Gravy",
    "You Need Jesus - bbno$, BABY GRAVY, Yung Gravy",
    "Ticking Away - bbno$, VALORANT, Grabbitz",
    "It Happpens (feat. bbno$) - bbno$, Little Big",
    "Nightmare on Peachtree Street (feat. Freddie Dredd) - bbno$, Yung Gravy, Freddie Dredd, BABY GRAVY",
    "Girlfriend - bbno$, Party Pupils, MAX, MILLI",
    "SOS - bbno$, KnowKnow",
    "Washed (feat. bbno$) - bbno$, Tiny Meat Gang",
    "TANGO - bbno$, Tommy Cash",
    "lil' freak - bbno$",
    "it boy - bbno$",
    "two - bbno$",
    "meant to be - bbno$",
    "check - bbno$",
    "antidepressants - bbno$",
    "boom - bbno$",
    "mary poppins - bbno$",
    "1-800 - bbno$, Ironmouse",
    "hot topic - bbno$",
    "in my zone - bbno$, VALORANT",
    "NSFW - bbno$",
    "FIGHT OR FLIGHT - bbno$, Zoey808",
    "yezzir - bbno$",
    "flex - bbno$, Sonn",
    "guarantee - bbno$, Sonn",
    "bad girl - bbno$, lentra, BAINS",
    "bulletproof - bbno$, lentra",
    "don't tell me shit - bbno$, lentra",
    "pennies up - bbno$, MIA GLADSTONE, Mr. Carmack, Promnite",
    "namaste - bbno$, Trippy Tha Kid, JASON RICH",
    "opus - bbno$, lentra, Juelz, So Loki",
    "jurassic - bbno$, lentra, TrippyThaKid",
    "banna - bbno$, lenta",
    "stucco - bbno$, lentra",
    "doubles - bbno$, Swerzie, Downtime",
    "roo doo - bbno$, lentra",
    "bunk - bbno$, lentra, Swerzie",
    "nursery - bbno$, lentra",
    "shinning - bbno$, lentra",
    "chess - bbno$, Konrad OldMoney",
    "seven - bbno$, TrippyThaKid, hollow",
    "thankful - bbno$, Y2K, Lewis Grant",
    "bad thoughts - bbno$",
    "on god - bbno$, Lewis Grant",
    "slop - bbno$",
    "shinning on my ex - bbno$, Yung Gravy",
    "I DON'T CARE CAUSE I GOOT MONEY!!!!!! - bbno$",
    "pop song - bbno$",
    "jimmy neutron - bbno$, LIL MAYO",
    "pouch - bbno$",
    "it gon'last - bbno$",
    "gone - bbno$",
    "Bandsville - bbno$, BABY GRAVY, Yung Gravy",
    "Justin Bieber Wrist - bbno$, BABY GRAVY, Yung Gravy",
    "Go Banannas - bbno$, BABY GRAVY, Yung Gravy, Spark Master Tape",
    "Off The Goop - bbno$, BABY GRAVY, Yung Gravy, Cuco",
    "Gasoline, Pt.2 - bbno$, BABY GRAVY, Yung Gravy, Spark Master Tape",
    "Welcome to Chillis - bbno$, BABY GRAVY, Yung Gravy",
    "Cadbury Creme - bbno$, BABY GRAVY, Yung Gravy, TrippyThaKid",
    "iunno - bbno$, BABY GRAVY, Yung Gravy",
    "Myrtle Beach Summer 1974 - bbno$, BABY GRAVY, Yung Gravy",
    "shinning on my ex - bbno$, BABY GRAVY, Yung Gravy",
    "rgb money - bbno$, lentra, Crosby",
    "astrology - bbno$, lentra",
    "admit it - bbno$, lentra TrippyThaKid",
    "keep up - bbno$, lentra, TrippyThaKid",
    "jack money bean - bbno$, Yung Gravy, lentra",
    "backwards - bbno$, lentra",
    "bubbles - bbno$, lentra, Crosby",
    "mahogany - bbno$, lentra",
    "man in the mirror - bbno$, lentra",
    "on one - bbno$, Blow Fever, ceo@business.net, lentra",
    "feeling good - bbno$, lentra, Gooch",
    "resume - bbno$",
    "black eyed peas - bbno$",
    "brainless - bbno$, lentra",
    "u mad! - bbno$",
    "2 time zones - bbno$, Night Lovell",
    "check up - bbno$, lentra",
    "i remember - bbno$",
    "tonight we fuckin' party - bbno$, ANH",
    "bag o die - bbno$",
    "chipotle - bbno$",
    "touch grass (feat. Yung Gravy) - bbno$, Yung Gravy",
    "let em know  - bbno$",
    "piccolo - bbno$",
    "robet patekson - bbno$",
    "b to the b - bbno$",
    "deadman (feat. Lil Toe) - bbno$, Lil Toe",
    "vasectomy - bbno$",
    "e-girl anthem - bbno$",
    "No Way Jose - bbno$, BABY GRAVY, Yung Gravy",
    "Super Smash Bros. - bbno$, BABY GRAVY, Yung Gravy",
    "back 2 back 2 back - bbno$, BABY GRAVY, Yung Gravy",
    "Pasadena - bbno$, BABY GRAVY, Yung Gravy",
    "You Need Jesus - bbno$, BABY GRAVY, Yung Gravy",
    "Onomatopeia - bbno$, BABY GRAVY, Yung Gravy",
    "swiper no swiping! - bbno$, BABY GRAVY, Yung Gravy",
    "Despicable G's - bbno$, BABY GRAVY, Yung Gravy",
    "Goodness Graciuos - bbno$, BABY GRAVY, Yung Gravy",
    "Touch Grass - bbno$, BABY GRAVY, Yung Gravy",
    "gigolo - bbno$",
    "Asthma Attack - NOAHFINNCE",
    "Underachiever - NOAHFINNCE",
    "STUPID - NOAHFINNCE",
    "parents (feat. Doll Skin) - NOAHFINNCE, DOll Skin",
    "LIFE'S A BIT - NOAHFINNCE",
    "PITY - NOAHFINNCE",
    "MIND BLANK NO THOUGHTS - NOAHFINNCE",
    "KICKIN TRASH - NOAHFINNCE",
    "WEIRDOS - NOAHFINNCE",
    "Clearveiw - NOAHFINNCE, Sophie Powers",
    "WORMS (In My Brain) - NOAHFINNCE",
    "I JUST WON'T CARE - NOAHFINNCE",
    "BETTER DAYS - NOAHFINNCE",
    "CHASHING DAYLIGHT - NOAHFINNCE",
    "TELL ME THAT YOU'RE OKAY - NOAHFINNCE",
    "AFTER THERAPY (feat. Hot Mulligan) - NOAHFINNCE, Hot Mulligan, Extra Large Holiday Card",
    "LALALA - NOAHFINNCE",
    "(NOT A) LOVE SONG - NOAHFINNCE, SOAP",
    "SEWN SHUT - SOAP",
    "No Point Pretending (Song For Tour) - NOAHFINNCE, Bears in Trees",
    "I KNOW BETTER - NOAHFINNCE",
    "GROWING UP ON THE INTERNET - NOAHFINNCE",
    "SCUMBAG - NOAHFINNCE",
    "Today - NOAHFINNCE, Rare Americans",
    "I Miss Having Sex But At Least I Don't Wanna Die Anymore - NOAHFINNCE, Hopelessly Devoted To You",
    "Boygirl - NOAHFINNCE, Pollyanna",
    "KINDA LOVE IT - NOAHFINNCE",
    "3 DAY HEADACHE - NOAHFINNCE",
    "ALEXITHYMIA - NOAHFINNCE",
    "SUBTITLES - NOAHFINNCE",
    "RISE AND GRING - NOAHFINNCE",
    "ALL THE SAME/NOT THE SAME - NOAHFINNCE",
    "SCUMBAG - NOAHFINNCE",
    "LOVELY LADIES - NOAHFINNCE",
    "GIBBERISH",
    "The Judge - NOAHFINNCE",
    "Chama La - AJR, T'y R.B, Houdini",
    "Celebrate - AJR, Ingrid Michaelson",
    "The Lotto - AJR, Ingrid Michaelson",
    "I'm Ready - AJR",
    "Woody Allen - AJR",
    "Growing Old On Bleeker Street - AJR",
    "AfterHours - AJR",
    "Buy You a Rose - AJR",
    "Infinity - AJR",
    "Alice by the Hudson - AJR",
    "Pitchforck Kids - AJR",
    "3AM - AJR",
    "Let The Games Begin - AJR",
    "Come Hang Out - AJR",
    "Weak - AJR",
    "Turing Out - AJR",
    "I'm Not Famous - AJR",
    "No Grass Today - AJR",
    "It's On Us (Benefiting the 'It's On Us' Campaign) - AJR",
    "Drama (Recorded at Spotify Studios NYC) - AJR",
    "Location (Recorded at SPotify Studios NYC) - AJR",
    "Pretender (feat. Lil Yachty & AJR) - AJR, Steve Aoki, Lil Yachty",
    "Dear Winter 2.0 - AJR",
    "Bang! (feat. Hayley Kiyoko-AhhHaa Remix) - AJR, Hayley Kiyoko, AhhHaa",
    "World's Smallest Violin (Sped Up) - AJR",
    "All My Favorite Songs (feat. AJR) - AJR, Weezer",
    "Way Less Sad - AJR",
    "Redord Player (with AJR) - AJR, Daisy the Great",
    "Weak (Nicolas Julian Remix) - AJR, Nicolas Julian",
    "I Won't - AJR",
    "The DJ Is Crying For Help - AJR",
    "The Dumb Song - AJR",
    "God is Really Real - AJR",
    "Yes I'm A Mess - AJR",
    "Betty - AJR",
    "The Plane That Never Lands - AJR",
    "A Dog Song - AJR",
    "I'm Sorry You Went Crazy - AJR",
    "The Big Goodbye - AJR",
    "Overture (Living Room) - AJR",
    "Infinity - AJR",
    "I'm Ready - AJR",
    "My Calling - AJR",
    "Thirsty - AJR",
    "Pitchfork Kids - AJR",
    "Woody Allen - AJR",
    "Livin' On Love - AJR",
    "Big White Bed - AJR",
    "The World Is A Marble Heart - AJR",
    "The Green And The Town - AJR",
    "Big Idea - AJR",
    "Growing Old On Bleeker Street - AJR",
    "Overture (The Click) - AJR",
    "Weak - AJR",
    "Sober Up (feat. Rivers Cuomo) - AJR, Rivers Cuomo",
    "Drama - AJR",
    "Turning Out - AJR",
    "No Grass Today - AJR",
    "Three-Thirty - AJR",
    "Call My Dad - AJR",
    "I'm Not Famous - AJR",
    "Netflix Trip - AJR",
    "Bud Like You - AJR",
    "Come Hang Out - AJR",
    "Burn The House Down - AJR",
    "Role Models - AJR",
    "Normal - AJR",
    "Next Up Forever - AJR",
    "Birthday Party - AJR",
    "100 Bad Days - AJR",
    "Don't Throw Out My Legos - AJR",
    "Break My Face - AJR",
    "The Entertainment's Here - AJR",
    "Karma - AJR",
    "Beats - AJR",
    "Wow, I'm Not Crazy - AJR",
    "Dear Winter - AJR",
    "Finale (Can't Wait To See What You Do Next) - AJR",
    "OK Overture - AJR",
    "Bummerland - AJR",
    "3 O'Clock Things - AJR",
    "My Play - AJR",
    "Joe - AJR",
    "Adventure Out There",
    "Bang! - AJR",
    "The Trick - AJR",
    "Ordinaryish People (feat. Blue Man Group) - AJR, Blue Man Group",
    "Humpty Dumpty - AJR",
    "Way Less Sad - AJR",
    "Christmas In June - AJR"
]
class Box{
    constructor(x,y,color, ){
        this.x = x;
        this.y = y;
        this.color = color;
        this.speed = 15;
        this.width = 1;
        this.height = 0.02;
        this.xDir = 5;
        this.yDir =5;
        this.output = Output
    }

    draw (){
            CTX.fillStyle = this.color
    CTX.fillRect (this.x,this.y,this.width, this.height)
    CTX.fillStyle ="black"
    CTX.fillRect (this.x+25,this.y,this.width - 50, this.height)
    CTX.fillStyle = this.color
    CTX.fillRect (this.x +37.5, this.y, this.width - 75, this.height)  
    }

    update (){
        let top = this.y;
        let bottom = this.y + this.height;
        let left = this.x;
        let right = this.x + this.width;
        let look = generateKt(thusy, );
        if (top < 0){
            this.yDir = 10;
            this.width = this.width * 0.5;
            this.height = this.height * 0.5;
            // this.y = 0;
             // @ts-ignore
          //  this.output.textContent = look;
        } else if (bottom > CANVAS.height){
            this.yDir = - 30;
            this.width = this.width * 2;
            this.height = this.height *2;
            // this.y= CANVAS.height - this.height;
            // @ts-ignore
            //this.output.textContent = look;
        }else if (left < 0){
            this.xDir = 10;
            this.width --;
            this.height --;
            // @ts-ignore
            this.output.textContent = look;
        } else if (right> CANVAS.width){
            this.xDir = - 20;
            // @ts-ignore
            //this.output.textContent = look;
            this.width = this.width * 1.5;
            this.height = this.height * 1.5;
        }

        this.x += this.xDir;
        this.y += this.yDir;
    };
};
/**@type{ Box[]} */
let boxes = [];
let colors = [
    "pink",
   "PaleVioletRed",
   "MediumVioletRed",
   "DeepPink",
   "HotPink",
   "LightPink",
   "DarkRed",
   "FireBrick",
   "Red",
   "Crimson",
   "LightSalmon",
   "DarkSalmon",
   "Salmon",
   "LightCoral",
   "IndianRed",
   "OrangeRed",
   "Tomato",
   "Coral",
   "Maroon",
   "HotPink",
    "HotPink",
    "DarkRed"
];
for (let i =0; i <= 15; i++){
    let color = colors[Math.floor(Math.random()*colors.length)]
    let box = new Box(0,0, color);
    box.x = Math.random() * CANVAS.width - 100;
    box.y = Math.random() * CANVAS.height -2;
    box.yDir = Math.floor(Math.random()* 5 + 5);
    box.xDir = Math.floor(Math.random()* 5 + 5);
    boxes.push(box);
};
//CTX.fillStyle = "black";
//CTX.arc(0+ 300, 0 + 200, 3, 0, 2 * Math.PI);
//CTX.fill();

function drawloop(){
    CTX.clearRect(0,0,CANVAS.width,CANVAS.height)
    boxes.forEach((b)=> {
        b.draw();
        b.update();
    });
    requestAnimationFrame(drawloop);
};
requestAnimationFrame(drawloop);