// This will be our last javascript file
console.log ("yes I did my work today....");
console.log ("don't you believe me?");
let username = "I totaly did what I am supposed to do, why are you looking at me like that";
console.log ("please belive me");
username= "no i'm not lying ";
let beliveMe = [
    "Omg I totally did my work",
    "Will you belive me please",
    "why is this making you sus...",
    "You can see my work, why are you doubting me",
    "Yes look HELLO FROM JAVASCRIPT, that has toatlly been here the whole time",
    "I have the documentation to prove it, just look at my code ignore when I commited it",
    "Omg what are you talking about? I have done what is needed of me",
    "My dog ate my work",
    "I am literly in the middle of finishing it"
]
let getRandomIndex = function (a) {
    let rand = Math.random() * a.length;
    return Math.floor(rand);
};
let getRandomWord = function (a) {
    return a[getRandomIndex(a)];
};
let generateExcuse = function (a) {
    let excuse =
        getRandomWord(a) +
        " "
    return excuse;
};
let IDidMyWork = true;
let IAmLying = false;
console.log ("See even the code know that I am not lying see... Am I lying?", IAmLying, "And also that I did my work is ", IDidMyWork);
console.log (username);
console.log (generateExcuse(beliveMe));
let mine = document.getElementById("My name");
let output = document.getElementById("name");
let MINE = document.getElementById("yes");
let myname = [
    "this is my name",
    "Whatever I want",
    "This is super code",
    "Blood on that bus",
    "nooo - piper ",
    "oh look there is a blimp"
];
const Ahhhh = "I am doing what I am supposed to"
console.log(Ahhhh)
let youClickedMe = [
    "look what you did",
    "This is your fault",
    "What happens next is becuase of you ",
    "You have to deal with the consequences",
    "Thanks for clicking me ",
    "Keep clicking me ",
    "You clicked me!",
    "You found out the truth now we have to take care of you",
    "Shh this won't be that bad",
    "You will be okay this is totally normal and fine",
    "Click me again I dare you ",
    "This will be fun at least for me",
    "Now you have to find out what you did wrong and solve "
]

let generateHA = function () {
    let ha =
        getRandomWord(youClickedMe) +
        " "
    return ha;
};

MINE.addEventListener("click", function () {
    let ha = generateHA();
    output.textContent = ha;
});

let generateName = function (a, ){
    let mynames =
        getRandomWord(a) +
    ""
    return mynames;
};
mine.addEventListener("click", function () {
    let name = generateName(myname, "is");
    output.textContent = name;
});
let profile = {
    truth: username,
    Lie: "This whole thing has been a lie",
    Truth : "I have never lied befrore"
};
console.log (profile);

let k = document.getElementById("k-pop");
let ks = [
 "Hey, hey, Hey hey, Hey Don't want you, need yo Yeah, I need you to fill me up 마시고 마셔 봐도 성에 차지 않아 Got a feeling that, oh, yeah You could be everything that That I need , taste so sweet Every sip makes me want more, yeah Don't want you, need you Yeah, I need you to fill me up 마시고 마셔 봐도 성에 차지 않아 Got a feeling that, oh, yeah You could be everything that That I need , taste so sweet  Every sip makes me want more, yeah Lookin' like snacks 'cause you got it like that Take a big bite, want another bite, yeah 너의 모든 걸 난 원해, 원해, 원해 너 말곤 모두 뻔해, 뻔해, 뻔해 When you're in my arms, I hold you so tight (So tight) Can't let go, no, no, not tonight 지금 당장 날 봐 시간 없잖아 넌 내꺼야 이미 알고 있잖아 'Cause I need you to need me I'm empty, you feed me so refreshing My little soda pop You're all I can think of Every drop I drink up You're my soda pop My little soda pop Cool me down, you're so hot Pour me up, I won't stop You're my soda pop My little soda pop My little soda pop. Uh, make me wanna flip the top 한 모금에 you hit the spot Every little drip and drop, fizz and pop, ah 소름 돋아 it's gettin' hot Yes, I'm sippin' when it's drippin' now It's done? I need a second round And pour a lot and don't you stop 'Til my soda pop fizzles out 꿈 속에 그려왔던 너 난 절대 놓칠 수 없어 널 원해 꼭 I waited so long for a taste of soda So, the wait is over, baby Come and fill me up Just can't get enough Oh You're all I can think of Every drop I drink up You're my soda pop My little soda pop (Yeah, yeah) Cool me down, you're so hot Pour me up, I won't stop (Oh, oh) You're my soda pop My little soda pop Ooh, ooh Ooh, ooh You're my soda pop Gotta drink every drop",
 "I was a ghost, I was alone, hah 어두워진 앞길속에 (Ah) Given the throne, I didn't know how to believe I was the queen that I'm meant to be I lived two lives, tried to play both sides But I couldn't find my own place Called a problem child 'cause I got too wild But now that's how I'm getting paid, 끝없이 on stage I'm done hiding, now I'm shining like I'm born to be We're dreaming hard, we came so far, now I believe We're goin' up, up, up, it's our moment You know together we're glowin' Gonna be, gonna be golden Oh, up, up, up with our voices 영원히 깨질 수 없는 Gonna be, gonna be golden Oh, I'm done hidin' now I'm shinin' like I'm born to be Oh, our time, no fears, no lies That's who we're born to be Waited so long to break these walls down To wake up and feel like me Put these patterns all in the past now And finally live like the girl they all see No more hiding, I'll be shining like I'm born to be 'Cause we are hunters, voices strong, and I know I believe We're goin' up, up, up, it's our moment You know together we're glowing Gonna be, gonna be golden Oh, up, up, up, with our voices 영원히 깨질 수 없는 Gonna be, gonna be golden Oh, I'm done hidin', now I'm shining like I'm born to be Oh, our time, no fears, no lies That's who we're born to be You know we're gonna be, gonna be golden We're gonna be, gonna be Born to be, born to be glowin' 밝게 빛나는 우리 You know that it's our time, no fears, no lies That's who we're born to be",
 "Takedown, takedown Takedown, down, down, down Takedown, takedown Takedown, down, down, down (It's a takedown) So sweet, so easy on the eyes, but hideous on the inside Whole life spreading lies, but you can't hide, baby, nice try I'm 'bout to switch up these vibes, I finally opened my eyes It's time to kick you straight back into the night 'Cause I see your real face and it's ugly as sin Time to put you in your place 'cause you're rotten within When your patterns start to show It makes the hatred wanna grow outta my veins I don't think you're ready for the takedown Break you into pieces in a world of pain, 'cause you're all the same Yeah, it's a takedown A demon with no feelings, don't deserve to live, it's so obvious I'ma gear up and take you down Woah-oh, da-da-da, down It's a takedown Woah-oh, da-da-da, down I'ma take it down Woah-oh, da-da-da, down It's a takedown Woah-oh, da-da-da, down (Take it down) It's a takedown, I'ma take you out, you break down like, What? It's a takedown, I'ma take you out and I ain't gonna stop 정신을 놓고 널 짓밟고 칼을 새겨놔 You'll be beggin' and cryin', all of you dyin', never miss my shot When your patterns start to show It makes the hatred wanna grow out of my veins I don't think you're ready for the takedown 당당하게 어둠 앞에 다가서 다 무너뜨려 Yeah, it's a takedown A demon with no feelings, don't deserve to live, it's so obvious I'ma gear up and take you downn Woah-oh, da-da-da, down It's a takedown Woah-oh, da-da-da, down I'ma take it down (Watch me do it, yeah) Woah-oh, da-da-da, down It's a takedown (Ooh) Woah-oh, da-da-da, down (Ooh) Oh, you're the master of illusion 나를 속이려 하지  Look at all the masses that you're foolin' But they'll turn on you soon, so how? How can you sleep or live with yourself? A broken soul trapped in a nastiest shell 영혼 없는 네 목숨을 끊으러 and watch you die You can try but you can't hide It's a takedown, I'ma take you out, you break down like, What? It's a takedown, I'ma take you out and I ain't gonna stop I'ma cut you open, lose control, then rip out your heart You'll be beggin' and cryin', all of you dyin' I'ma gear up and take you down Woah-oh, da-da-da, down (La-la-la) It's a takedown Woah-oh, da-da-da, down (Yeah-yeah, yeah-yeah, yeah) I'ma take it down Woah-oh, da-da-da, down (Ooh) It's a takedown (Ooh) Woah-oh, da-da-da, down (Watch me do it, yeah) Take it down",
 "Pray for me now Pray for me now (Dies irae) Pray for me now (Illa) Pray for me now (Vos solve in) Pray for me now (Favilla) Pray for me now (Maledictus) Pray for me now (Erus) Pray for me now (In flamas) Pray for me now (Eternum) I'll be your idol Keeping you in check (Uh), keeping you obsessed (Uh) Play me on repeat, 끝없이 in your head Anytime it hurts (Uh), play another verse (Uh) I can be your sanctuary Know I'm the only one right now (Now) I will love you more when it all burns down More than power, more than gold (Yeah) Yeah, you gave me your heart, now I'm here for your soul I'm the only one who'll love your sins Feel the way my voice gets underneath your skin Listen 'cause I'm preachin' to the choir Can I get the mic a little higher? Gimme your desire I can be the star you rely on (You rely on) 내 황홀의 취해, you can't look away (Hey) Don't you know I'm here to save you Now we runnin' wild Yeah, I'm all you need, I'ma be your idol Uh Uh Uh, 빛이나는 fame, 계속 외쳐, I'm your idol Thank you for the pain 'cause it got me going viral Uh, yeah, 낫지 않는 fever, makin' you a believer 나를 왜 넌 존재하는 idol? Don't let it show, keep it all inside The pain and the shame, keep it outta sight Your obsession feeds our connection 이 순간 give me all your attention You know I'm the only one who'll love your sins Feel the way my voice gets underneath your skin  Listen 'cause I'm preachin' to the choir Can I get the mic a little higher? Gimme your desire I can be the star you rely on (You rely on) 내 황홀의 취해, you can't look away (Yeah) Don't you know I'm here to save you Now we runnin' wild Yeah, I'm all you need, I'ma be your idol Be your idol Living in your mind now Too late 'cause you're mine now I will make you free When you're all part of me (Listen 'cause I'm) Preaching to the choir (Now) Can I get the mic a little higher? Gimme your desire Watch me set your world on fire 내 황홀의 취해, you can't look away (Hey) No one is coming to save you Now we runnin' wild You're down on your knees, I'ma be your idol",
 "Nothing but the truth now Nothing but the proof of what I am The worst of what I came from, patterns I'm ashamed of Things that even I don't understand I tried to fix it, I tried to fight it My head was twisted, my heart divided My lies all collided I don't know why I didn't trust you to be on my side I broke into a million pieces, and I can't go back But now I'm seeing all the beauty in the broken glass The scars are part of me, darkness and harmony My voice without the lies, this is what it sounds like Why did I cover up the colors stuck inside my head? I should've let the jagged edges meet the light instead Show me what's underneath, I'll find your harmony The song we couldn't write, this is what it sounds like We're shattering the silence, we're rising defiant Shouting in the quiet, you're not alone We listened to the demons, we let them get between us But none of us are out here on our own So, we were cowards, so, we were liars So, we're not heroes, we're still survivors The dreamers, the fighters, no lying, I'm tired But dive in the fire and I'll be right here by your side We broke into a million pieces, and we can't go back But now we're seeing all the beauty in the broken glass The scars are part of me, darkness and harmony My voice without the lies, this is what it sounds like Why did we cover up the colors stuck inside our head? Get up and let the jagged edges meet the light instead Show me what's underneath, I'll find your harmony Fearless and undefined, this is what it sounds like This is what it sounds like (Oh, oh, oh) Hey, hey This is what it sounds like (Oh, oh, oh) Hey, hey This is what it sounds like (Oh, oh, oh) Hey, hey Oh, this is what it... this is what it... This is what it sounds like We broke into a million pieces, and we can't go back But now I'm seeing all the beauty in the broken glass The scars are part of me, darkness and harmony My voice without the lies, this is what it sounds like Why did we cover up the colors stuck inside our head? Get up and let the jagged edges meet the light instead Show me what's underneath, I'll find your harmony Fearless and undefined, this is what it sounds like My voice without the lies, this is what it sounds like Fearless and undefined, this is what it sounds like Truth after all this time, our voices all combined When darkness meets the light, this is what it sounds like",
 "I tried to hide but something broke I tried to sing, couldn't hit the notes The words kept catching in my throat I tried to smile, I was suffocating though But here with you, I can finally breathe You say you're no good, but you're good for me I've been hoping to change, now I know we can change But I won't if you're not by my side Why does it feel right every time I let you in? Why does it feel like I can tell you anything? All the secrets that keep me in chains and All the damage that might make me dangerous You got a dark side, guess you're not the only one What if we both tried fighting what we're running from?  We can't fix it if we never face it What if we find a way to escape it? We could be free Free We can't fix it if we never face it Let the past be the past 'til it's weightless Ooh, time goes by, and I lose perspective Yeah, hope only hurts, so I just forget it But you're breaking through all the dark in me When I thought that nobody could And you're waking up all these parts of me That I thought were buried for good Between imposter and this monster I been lost inside my head Ain't no choice when all these voices Keep me pointing towards no end It's just easy when I'm with you No one sees me the way you do I don't trust it, but I want to I keep coming back to Why does it feel right every time I let you in? Why does it feel like I can tell you anything? We can't fix it if we never face it What if we find a way to escape it? We could be free Free We can't fix it if we never face it Let the past be the past 'til it's weightless Oh, so take my hand, it's open Free, free What if we heal what's broken? Free, free I tried to hide, but something broke I couldn't sing, but you give me hope We can't fix it if we never face it Let the past be the past 'til it's weightless",
 "Ugh, you came at a bad time But you just crossed the line You wanna get wild?  Okay, I'll show you wild Better come right, better luck tryin', gettin' to our level 'Cause you might die, never the time, tryna start a battle Bleeding isn't in my blood, 뼈속부터 달라서 [ppyeosokbuteo dallaseo]  Beating you is what I do-do-do, yeah Body on body I'm naughty, not even sorry And when you pull up, I'll pull up A little late to the party (Na-na-na-na) Locked and loaded, I was born for this There ain't no point in avoiding it Annoyed? A bit 불을 비춰 다 비켜, 네 앞길을 뺏겨 [Bureul bichwo da bikyeo, ne apgireul ppaetgyeo] Knocking you out like a lullaby Hear that sound ringing in your mind Better sit down for the show 'Cause I'm gonna show you how it's done-done-done (Hey) Huntrix don't miss How it's done-done-done (Hey) Huntrix don't quit How it's done-done-done Run, run, we run the town Whole world playin' our sound Turnin' up, it's going down Huntrix show this, how it's done-done-done Yeah, something about when you come for the crown That's so humbling, huh? 갑자기 왜 그래? 먼저 건드려, 왜? [Gapjagi wae geurae? Meonjeo geondeuryeo, wae?] 이제야 포기해, what? [Ijeya pogihae, what?] Nothing to us Run up, you're done up, we come up From sunup to sundown, so come out to play Won either way, we're one in a million We killin', we bring it, you want it? Okay Heels, nails, blade, mascara Fit check for my napalm eracNeed to beat my face, make it cute and savage Mirror, mirror on my phone, who's the baddest? (Us, hello?) Knocking you out like a lullaby Hear that sound ringing in your mind Better sit down for the show 'Cause I'm gonna show you (I'm gonna show you) (I'm gonna show you) How it's done-done-done I don't talk, but I bite, full of venom (Uh) Spittin' facts, you know that's How it's done-done-done Okay, like, I know I ramble But when shootin' my words, I go Rambo Took blood, sweat, and tears, to look natural (Uh) That's how it's done-done-done Hear our voice unwavering 'Til our song defeats the night Makin' fear afraid to breathe 'Til the dark meets the light (how it's done-done-done) Run, run, we run the town (done-done-done) Whole world playin' our sound (done-done-done) Turnin' up, it's going down (done-done-done) Huntrix, show this how it's done-done-done We hunt you down (down) (Done-done-done) We got you now (Got you now) (Done-done-done) We show you how-how-how (Show you how) Huntrix, don't miss, how it's done-done-done",
];
let generateK = function (a, ){
    let mk =
        getRandomWord(a) +
    ""
    return mk;
};
k.addEventListener("click", function () {
    let ok = generateK(ks, );
    output.textContent = ok;
});
let stay = document.getElementById("strayKids");
let stray = [
    "Hip-hip (Hooray) Hip-hip (Hooray) Hip-hip, hip-hip Yuh, yuh, yuh, yuh We're moving forward with maximum power And we're gonna dominate, pop it 장식하지, big news, topic 경험치는 수많은 trophy No one, nobody can stop me 수많은 억까는 도움닫기 Jump up, jump up Like a pop-up, toaster, lift Working off time That ratio got us going worldwide (Worldwide) Thirsty day and night They put us in the desert but we survive Busy giving our light Unlike them, we're getting all the spotlight Listen to the war cry Karma, karma, karma, karma Hip-hip (Hooray) Hip-hip (Hooray) Hip-hip, hip-hip Karma, karma, karma, karma Ceremony Hip, hip, hip, hip, hip, hip, hip (Hooray) Woah, ceremony Hip, hip, hip, hip, hip, hip, hip (Hooray) We did it, 소리 질러, wow Slide, 반지 kiss, muah 받아 내 상 마치 부케 봐라 내 두 손은 두둑해 바쁠 때 눈코 뜰 새가 없대 But that's okay, 소감을 또 준비해 I feel like 우주 붕, 붕, 붕 (Ho) You and I, let's go celebrate 이 상태는 엄청나 삐끗삐끗 터지는 emergency We don't care, show you 나 버젓이 여기저기, look at our paradise 어디까지 갈지 예상 밖이야 시끌시끌 북적해 우리 근처는 언제나 소음 발생이야 Working off time That ratio got us going worldwide (Worldwide) Thirsty day and night They put us in the desert but we survive Busy giving our light Unlike them, we're getting all the spotlight, yeah Listen to the war cry Karma, karma, karma, karma Hip-hip (Hooray) Hip-hip (Hooray) Hip-hip, hip-hip Karma, karma, karma, karma Ceremony Hip, hip, hip, hip, hip, hip, hip (Hooray) Woah, ceremony Hip, hip, hip, hip, hip, hip, hip (Hooray) Yeah, we gon' celebrate 'cause we got good Karma, karma, karma, karma Calmer, calmer, calmer, that's our Karma, karma, karma, karma Yeah, we gon' celebrate 'cause we got good Karma, karma, karma, karma Calmer, calmer, calmer Oh, ceremony",
    "사건 발생 잊지 못할 사건 치명적인 매력에 홀라당 빠져 자꾸 나를 자극하는 넌 출처가 없는 문제야 풀어야 할 숙제야 Can I be your boyfriend? 너를 대하는 태도 거짓 하나 없어 no cap 너에게 하고 싶은 말로 가득 찼어 my case 완벽함 앞에 어떤 말로도 부족해 You got me losing patience 걷잡을 수 없는 emotion 떠올라 네 모습 I never feel alright 수많은 감정이 충돌해 왜 이래 Rolling in the deep inside my head You got me bad 무장해제 신속하게 네게로 moving, on my way Why do I keep getting attracted 자석 같이 끌려가 I cannot explain this reaction 이것밖에 143 Why do I keep getting attracted 네 모습만 떠올라 I cannot explain this emotion 143 I LOVE YOU A B C D E F G I Wanna send my code to you 8 letters is all it takes And I'm gonna let you know oh 너 말곤 높이 쌓아뒀지 barricade (barricade) 원하는 대로 불러도 돼 Code name (call me baby) 욕심이래도 되고 싶어 soulmate (whoo) 이 맘은 점점 더 upgrade 'cause You got me losing patience 걷잡을 수 없는 emotion 떠올라 네 모습 I never feel alright 수많은 감정이 충돌해 왜 이래 Rolling in the deep inside my head You got me bad무장해제 신속하게 네게로 moving, on my way Why do I keep getting attracted 자석 같이 끌려가 I cannot explain this reaction 이것밖에 143 Why do I keep getting attracted 네 모습만 떠올라 I cannot explain this emotion 143 I LOVE YOU Heartbeat 나의 모든 상태 지금 위기 (위기) 너의 모습 ain't no 'false' 나의 속맘 다시 repeat (repeat) Walking next to you but I'm fallin 더 깊게 빠져들어 끌리지 You're pulling me deeper and deeper I try to get out but I can't stop Can I be the one? Yeah I'll be the one 무모하게 도전해 오그라드는 표현 머릿속이 띵하고 무감정은 손절 Moving, I'm on my way Why do I keep getting attracted 네 모습만 떠올라 I cannot explain this emotion 143 I LOVE YOU Why do I keep getting attracted 자석 같이 끌려가 I cannot explain this reaction (이것밖에) I'm gonna let you know (know) That I'm just gonna go (go) And hold you so I'm never letting go I'm gonna let you know (know) That I'm just gonna go (just go) Yeah 난 너에게로 지금 출발합니다 바로 like I'm Never letting go oh I cannot explain this emotion 143 I LOVE YOU",
    "Boom, boom, chk, chk, boom (Brrah) 정중앙 흑색의 저 점도 맞춰 내 재빠른 계획도 허점 없이 완벽한 판도 위에서 춤춰 내 plan대로 keep going Sick of this life, it's regular 승리를 너무 과식했지 배불러 (Ayy) 산책도 할 겸 허리띠 매 둘러 우린 우주로 나머지 전부 kneel, I'm strong  Yeah, yeah, yeah, yeah, 안 되는 것 없이 I do it (Do it) Just pull out my trigger, I got that (Woo) I'ma pop, pop, pop, take a shot, yeah Shoot down my goals one by one, I snipe them Filling up my truck Yeah, you want that ride (Boom) Hit you like a truck I'ma make you fly (Boom) Vamos, I know that you want it (Boom) Lobos, we cannot stop hunting (Boom) Ra-ta-ta-ta, I'ma make it Boom, boom, chk, chk, boom (Boom) Vamos, I know that you want it (Boom) Chaos, we so catastrophic (Boom) Ra-ta-ta-ta, I'ma make it Boom, boom, chk, chk, boom  (Boom) Cliché 파괴 자체가 더 cliché (Boom) 나에 대한 견해 전부 유지해 (Boom) 바뀐 건 없어 I'm not a changed man 내 행보는 여전히 그다음 level에만 대입해 목표치에 한 발씩  한발치 더 다다랐지 I'm the owner of my goal, 주인 잘 만난 복 I make it right, 영점 조준 clear 정적을 깨 버리지 나의 trigger, fire (Fire) 저 끝까지 과녁을 더 위로 올려 (My amigo) Filling up my truck Yeah, you want that ride (Boom) Hit you like a truck I'ma make you fly  (Boom) Vamos, I know that you want it (Boom) Lobos, we cannot stop hunting (Boom) Ra-ta-ta-ta, I'ma make it Boom, boom, chk, chk, boom (Boom) Vamos, I know that you want it (Boom) Chaos, we so catastrophic (Boom) Ra-ta-ta-ta, I'ma make it Boom, boom, chk, chk, boom  깊이 더 파고들어 My bullet goes 탕탕탕 이건 la vida loca 이건 good shot, shot, shot 깊이 더 파고들어 My bullet goes 탕탕탕 이건 la vida loca Boom, boom, chk, chk, boom",
    "뚜뚜뚜뚜뚜뚜 웃겨? 머리가 아픈 게 웃겨? A급 감성이 웃겨? 하 CHEESE 옷차림 헤어스타일 내 눈엔 폼나지 외부인 외계인 취급은 익숙해 난 뻔뻔하지 Funny funny 날 보고 웃었다면 더 빵빵 터지게 해줄게 딱 봐도 born to be 광대 다 같이 붕붕 날아볼래? Hold up 우습기에 굳었지 파마산 치즈 너네 한마디면 분위기 freeze개그 코드가 모자라 치즈- Jeez Jeez  I love what you hate 네가 뭐라든 재밌거든 다 Thank you, I love it 헛소리 대판 벌인다검지 중지 약지 새끼 what 검지 중지 약지 새끼 접어 what 씹고 뜯고 맛보다 즐길 거면서 What's the matter? 정색 말고 인상 좀 피자 like 반죽 CHEESE 뚜뚜뚜뚜뚜뚜 웃겨? 머리가 아픈 게 웃겨? A급 감성이 웃겨? 웃겨 CHEESE 비둘기 까치가 웃겨? 까마귀 소리가 웃겨? A급 감성이 웃겨? 웃겨 CHEESE Yeah yeah yeah yeah yeah yeahYeah yeah yeah yeah 웃어봐 Yeah yeah yeah yeah yeah yeah yeah yeah yeah CHEESE Yeah yeah yeah yeah yeah yeah Yeah yeah yeah yeah 웃어봐 Yeah yeah yeah yeah yeah yeah Yeah yeah yeah CHEESE  웃기지 내 걸음걸이 우리가 만든 거 다 놀림거리 Look, why did you say it like that? 혓바닥 shotgun 장전 Click Clack Bang 그래 생각해요 네 맘대로 이러쿵저러쿵 I don't know Do what you do, out of 안중 내가 내려가는 건 걍 네 개꿈  검지 중지 약지 새끼 what 검지 중지 약지 새끼 접어 what 씹고 뜯고 맛보다 즐길 거면서 What's the matter? 정색 말고 인상 좀 피자 like 반죽 “자 하나 둘 셋” CHEESE  뚜뚜뚜뚜뚜뚜 웃겨? 머리가 아픈 게 웃겨? A급 감성이 웃겨? 웃겨 CHEESE 비둘기 까치가 웃겨? 까마귀 소리가 웃겨? A급 감성이 웃겨? 웃겨 CHEESE Blue Cheese Cheddar Cheese Parmesan Cheese CHEESE 뚜뚜뚜뚜뚜뚜 웃겨? 머리가 아픈 게 웃겨? A급 감성이 웃겨? 웃겨?! CHEESE  Yeah yeah yeah yeah yeah yeah Yeah yeah yeah yeah 웃어봐 Yeah yeah yeah yeah yeah yeah Yeah yeah yeah CHEESE Yeah yeah yeah yeah yeah yeah Yeah yeah yeah yeah 웃어봐 Yeah yeah yeah yeah yeah yeah Yeah yeah yeah CHEESE",
    "내 삶은 밑바닥 낭떠러지 어두운 터널 속을 걷고 있어 내게 잔인하고 두려운 하루를 홀로 버티고 있어 멀러져 가는 교실복도 낯선 길 위에 지지리도 복도 없지 내가 맞는 길을 가는가에 답 할 지도도 하나 없이 위로 가는 길은 절대 다신 뒤로 가기 싫은 막막한 미로야 피눈물 대신 피땀 흘리며 나를 위로해 사람들은 내게 말해 그 정도의 고비는 지나가는 소나기라고 성공을 낚으려면 두려워도 실패라는 덫을 깔라고 그래 나는 고통이란 미끼를 덥석 문채 방황하는 거야 지친 열정의 날개를 잠시 접어둔 채 내 삶은 밑바닥 낭떠러지 어두운 터널 속을 걷고 있어 내게 잔인하고 두려운 하루를 홀로 버티고 있어 손을 내 밀어도 날 잡아줄 사람은 아무도 없어 내 아픔 내 눈물을 타고 위로 빠져나가고 있어 I'm on a hellevator My hellevator I'm on a hellevator My hellevator I'm on a hellevator 아무것도 없어 날 위한 손길은 걱정 하나 없이 차가운 말들뿐 엉터리 꿈은 좀 접어 포기란 말들이 내 귀를 때려가며 절망감만 커져가 희망이란 하늘을 주변 사람의 손으로 가린다 날 살려 기도하며 버티고 있어 날 째려보는 따가운 시선들에 실성하지 하네 마네 잘 되어 봤자 누군가의 광대 로 밖에 안 남을 넌 가수라는 직업은 집어 쳐 그 말을 들으며 약해져만 가는 내 자신을 밀쳐 더 내 삶은 밑바닥 낭떠러지 어두운 터널 속을 걷고 있어 내게 잔인하고 두려운 하루를 홀로 버티고 있어 손을 내 밀어도 날 잡아줄 사람은 아무도 없어 내 아픔 내 눈물을 타고 위로 빠져나가고 있어 I'm on a hellevator My hellevator I'm on a hellevator My hellevator I'm on a hellevator 찾아내 출구는 어디에 어둠 속에 갇혀있던 나를 끌어내 좀 더 발악해 이곳을 run away I'm on the hellevator 난 올라갈게 어두웠던 내 과거 탈출해 내 깜깜했던 앞길을 비춰 미쳐버릴 듯 지겨운 시간 잊혀져 버릴 듯 이 길을 뛰어 외면하던 새로운 시작의 종소리가 울리며 나는 올라탔지 내 손을 잡고 펜트하우스로 데려다 줄 my hellevator I'm on a hellevator My hellevator I'm on a hellevator",
    "(What the—) I was born to take off (Woo) You know my life is tied up (Woo) 더 길게 뻗어갈 곡선 부딪혀 얻어낸 beautiful pain, yeah 와서 대신 들어보면 일초 만에 쿵 어깨에 들린 짐 덩이와 자부심의 무게 이런 모습에 거부감이 느껴진다면, hm 어떤 이의 노력에 그런 감정이라면 문제 Put the embers out like a firetruck Ashes tasting like sweet fudge Censor out the fire 'cause we don't give a All we do is have fun Doesn't matter what they say, I'm driven Filter out their ways and listen Music to my ears, your silence I can't hear you Fail (삐처리), frail (삐처리) Lazy (삐처리), hazy (삐처리) Rumors (삐처리), boomers (삐처리) Yada, yada, noise cancellation Fail (삐처리), bail (삐처리) Shut up (삐처리) (What the—) Crisis (삐처리), hardship (삐처리) Yada, yada, noise cancellation 성급히 만들어낸 가짜 prize 커리어에서 삐처리 My passion, my action 성공에 featuring 성취감은 커져 crescendo 일어나 기적이 포기와는 불협화음 pitch (Mm, mm, mm) 실없지 피치 못할 사정이란 핑계 지침 자기 합리화 잠이나 자라고 해 취침 불어오는 늦바람을 요리조리 피해 다녀 주어지는 기회라면 모조리 다 pitch Don't care, 잡소리 다 신경 쓰면, there's no way 삿대질과 평가질 thank you, 더 욕해 내 수명은 늘어나 이게 내 숙명이라고 받아들인 지는 이미 오래 Put the embers out like a firetruck Ashes tasting like sweet fudge Censor out the fire 'cause we don't give a All we do is have fun (Yeah) Doesn't matter what they say, I'm driven Filter out their ways and listen Music to my ears, your silence I can't hear you 누군가 남긴 것들 잔반 처리 그딴 거 필요 없어 너나 많이 (너나 많이) 어쩌고 저쩌고는 진저리 (Mm) 나지 그리 많은 말은 전부 삐처리 왈가왈부 다 block, 묵음 come show your face, man 탄탄하게 쌓던 top from the basement I'll find you and kill you like the movie, Taken (Tell 'em) Fail (삐처리), frail (삐처리) Lazy (삐처리), hazy (삐처리) Rumors (삐처리), boomers (삐처리) Yada, yada, noise cancellation Fail (삐처리), bail (삐처리) Shut up (삐처리) (What the—) Crisis (삐처리), hardship (삐처리) Yada, yada, noise—",
    "On the street Ow The burning tires keep, rolling Hey 엑셀 밟아 더 거칠게, 치솟는 RPM 매일이 장 날이지 D-day, 일단 가는 거야 달려, right now 달아오른 트랙 위로 빠라바빠라바빠라바빠빰 I'm not tired, tired, tired, 수많은 feel 중 피곤은 goodbye Tire, tire, tire, 쉴 틈 없이 또 굴러가는 두 발 Fire, fire, fire, 마찰력에 불이 붙어도 다 무탈 역풍을 맞아도 벌려 두 팔, 이-공-일-팔-부터 난 일탈 I'm runnin' on the street, you'll never feel this way Don't disturb me, just look at me The burnin' tires keep rolling like a stage effect I don't know where the end will be (Rollin', rollin') Ba-ra-ba-bam, I'm runnin' until the end Ba-ra-ba-bam, get out of my way Ba-ra-ba-bam, I'm burnin' until the end Ba-ra-ba-bam, get out of my way 지구 한 바퀴 다음 두 바퀴 세 바퀴 넘어가도 닳지 않아 내 바퀴 멈출 수 없는 속도 타들어 가 내 목도 더 빨라지는 내 BPM 심장은 계속 boom 비포장도로 위를 달려가지 신발 끈을 꽉 묶은 대신에 고삐를 풀어 숨이 가빠도 끊기진 않지 제어가 불가능한 대형 트럭 누가 날 막아 나도 날 못 막아 어느 것도 마다 하지 않아 할까? 말까? 갈까? 말까? 하다 말다 하는 그때마다 넌 그냥 이 노랠 틀어 Ba-ra-ba-bam, I'm runnin' until the end Ba-ra-ba-bam, get out of my way Ba-ra-ba-bam, I'm burnin' until the end Ba-ra-ba-bam, get out of my way Rolling on the street, rolling on the street 해가 저물고 밤이 와도 난 못 멈춰 Rolling on the street, rolling on the street 가진 적 없는 별들에 이끌려, all night long Ba-ra-ba-bam, I'm runnin' until the end Ba-ra-ba-bam, get out of my way (Hey) Ba-ra-ba-bam, I'm runnin' until the end Ba-ra-ba-bam, get out of my way Ba-ra-ba-bam, I'm burnin' until the end Ba-ra-ba-bam, get out of my way I'm runnin' on the street, you'll never feel this way (Ba-ra-ba-bam, I'm runnin' until the end) Don't disturb me, just look at me (Ba-ra-ba-bam, get out of my way) The burnin' tires keep rolling like a stage effect (Ba-ra-ba-bam, I'm burnin' until the end) I don't know where the end will be (Rollin', rollin') (Ba-ra-ba-bam, get out of my way)",
    "'네 손님' 어서 오십시오 이 가게는 참 메뉴가 고르기도 쉽죠 뭘 시켜도 오감을 만족하지 하지 지나가던 나그네, 비둘기까지 까치까지 까마귀들까지 Cooking a sauce 입맛대로 털어 음미하고 lick it 말해 bon Taste so good 반응은 모두 쩔어 But 모두 자극적인 거 I want it till 다 먹일 때까지 연구하지 cross boundaries 경계 따위 없어 마치 창조하듯 소리를 만들지 그저 계속 만들어가 새롭게 Because we're one of a kind 누구도 따라 할 수 없는 our own game 시작부터 다 우리 꺼 잠깐 떠나간다 해도 결국 다시 찾게 될 열기가 식지 않는 메뉴 지금부터 싹 다 입맛에다 때려 박아 DU DU DU DU DU DU 이게 우리 탕 탕 탕탕 DU DU DU DU DU DU 이게 우리 탕 탕 탕탕 지금 바로 눈에 불을 켜 I just wanna taste it, make it hot 새로운 불판 위에 track을 달궈 메뉴 골라 call me up 원하는 걸로 다 serve DU DU DU DU DU DU Cookin' like a chef I'm a 5 star 미슐랭 '미'의 정점을 찍고 눈에 보여 illusion Whoo 첨 느꼈지 이런 감정 놀랄 거야 gonna shock 바로 감전 자물쇠 따 싹 다 unlock Idea bank 머릿속을 털어 털어 비밀재료가 궁금하다면 사실 우린 그딴 거 안 써 그저 계속 만들어가 새롭게 Because we're one of a kind 누구도 따라 할 수 없는 our own game 시작부터 다 우리 꺼 잠깐 떠나간다 해도 결국 다시 찾게 될 열기가 식지 않는 메뉴 지금부터 싹 다 입맛에다 때려 박 DU DU DU DU DU DU 뭐든 그냥 집어넣어 눈치 보지 말고 더 망설이지 말고 부어 비벼 비벼 '네 손님' DU DU DU 이게 우리 탕 탕 탕탕 DU DU DU DU DU DU 이게 우리 탕 탕 탕탕 DU DU DU DU DU DU 어서 오십시오 이 가게는 참 메뉴가 고르기도 쉽죠 뭘 시켜도 오감을 만족하지 하지 지나가던 나그네, 비둘기까지 까치까지 DU DU DU DU DU DU",
    "Welcome to 극락 (락) 날벼락 (락) 도시의 락 (락) 즐기면 그만 (락) 없지 고난 (락) 역경의 밤 (락) 지새우면 끝 고생 끝에 낙 (락) 잡생각 고민 오키도키 안 해 뻘짓 도피도피 여긴 벌집 벌투성이 피할 수 없음 쏘이고 보자 고막 터뜨려 Bang, bang 흠뻑 젖은 머리 헤드뱅잉 졸라맸던 허리띠 더 꽉 매고 움직여 쉴 새 없게 주제넘게란 말 집어치운 채 즐김은 위아래 없는 축제 행복 지수 측정 불가 Good day Lock, lock, unlock Just feel the rhythm of the world 'Cause we will make it rock 몸부림치며 Roll 냅다 던져버려 맞닥뜨려 세상의 소음 La-la-la-la, la, la-la-la-la Just feel the rock, we let it rock (La-la-la-la, la, la-la-la-la) Just feel the luck, we let it rock (La-la-la-la, la, la-la-la-la) 노랫가락 락락락 미치도록 La-la-la-la La-la-la-la, la, la-la-la-la Inhale 빨리 산소 호흡해 바쁘게 움직여야 해 몸 Guitar, bass, drums 또 새까맣게 칠하지 Nails도 We gon' rock, rock 움직임은 Don't stop, stop Go for rock Yeah, we tick-tock, boom, chiki-ta 여기 Mic 위에 Shout 다 즐겨라 걍 음악이다 걸어 Lock 근심에 이 노래는 삼 머리 풀어 장르부터 즐거울 락 (Oh, yeah) 이것저것 빈 무대에 섞어 저기 반응 약해 빨리 변신해 Stunner Bet you've never seen a stage like this 번쩍 떠 버리지 눈이 남은 기대들마저 털어 Just feel the rhythm of the world 'Cause we will make it rock 몸부림치며 Roll 냅다 던져버려 맞닥뜨려 세상의 소음 가리지 않아 So sick 어디든 흘러나오는 대로 Move and show it 낮이고 밤이고 낙으로 살아가지 Oh 쉿 피할 곳 없이 부딪혀 쾅쾅 쳐 대자고 정적과 부정적 에너지 타파 La-la-la-la, la, la-la-la-la La-la-la-la, la, la-la-la-la Just feel the rock, we let it rock (La-la-la-la, la, la-la-la-la) Just feel the luck, we let it rock (La-la-la-la, la, la-la-la-la) 노랫가락 락락락 미치도록 La-la-la-la Rock and roll We dancing till we fall No stopping, here we go 24/7, keep it going on Rock and roll We dancing till we fall No stopping, here we go No stopping, here we go Here we go",
    "여긴 Seoul 특별시 수많은 기적을 일으켰지= 가려진 별들 사이 떠오르는 특별 (별, 별, 별, 별) 별난 것투성이 변함없지 번화하는 거리 거리거리마다 걸리적거리는 거 Clean it up, clean it up, get back 겉만 번지르르 텅텅 빈 깡통 Kick it, kick it, kick it Swerving I'm speeding on serpent road Luxurious like I'm an S-class Best of the best on first class I'm up above the world, so high I'll be there shining day and night They wonder how my spotlight is so bright Counting stars 특별의 별의 별의 별의 별의 별의 별의 별난 놈, that's me 별의 별의 별의 별의 별의 별의 별 일이 my work (Bling, bling) Everyday, 빛깔 뻔쩍 빛깔 뻔쩍 빛깔 뻔쩍해 class는 특  빛깔 뻔쩍 빛깔 뻔쩍 빛이 번져 더욱 빛나는 star 힙합 스텝 큼지막이 밟지 특출난 게 특기 내 집처럼 드나들지 특집 작업실은 안 부러워 특실 득실득실거려 독보적인 특징 두리번두리번 어중떠중 띄엄띄엄 보는 애들이 뻔쩍뻔쩍 빛나는 것들만 보면 달려 버릇이, no, no 빛나는 걸 쫓기보단 빛나는 쪽이 되는 게 훨씬 폼 잡기 편해, shine like a diamond, 'kay? Swerving I'm speeding on serpent road Luxurious like I'm an S-class Best of the best on first class I'm up above the world, so high I'll be there shining day and night They wonder how my spotlight is so bright Counting stars 특별의 별의 별의 별의 별의 별의 별의 별난 놈, that's me 별의 별의 별의 별의 별의 별의 별 일이 my work (Bling, bling) Everyday, 빛깔 뻔쩍 빛깔 뻔쩍 빛깔 뻔쩍해 class는 특 빛깔 뻔쩍 빛깔 뻔쩍 빛이 번져 더욱 빛나는 star I feel like the brightest star 빛이 쏟아지는 밤 하늘을 바라보면 내 모습 수놓아져 있어, yeah, yeah 떨어지지 않고 한 자리에서 거뜬하게 stay해, yeah 빛날 광에 사람인 그게 바로 우리 소개말, we're special, yeah Stray Kids, 내 뒤의 팀은 특수부대 Stage 위 그 자체로 이건 특별 무대  따로 필요 없지 축제 절제 따위 필요 없이 고삐 풀 때 Limited edition, 특이한 건 특별해져 불투명함은 분명하게 바꿔 거듭 되새겨 눈에 띄는 텐션 몰입하는 객석 우리 빛이 하나가 돼 여기 모든 곳을 밝혀 Counting stars, 특 (Counting stars, 특) Feeling extra (Bling, bling) Everyday, 빛깔 뻔쩍 빛깔 뻔쩍 빛깔 뻔쩍해 class는 특 빛깔 뻔쩍 빛깔 뻔쩍 빛이 번져 더욱 빛나는 star",
    "얼음 땡 얼음 땡 아침 먹고 땡 점심 먹고 땡 저녁 먹고 땡 삼시 세끼 다 챙겨도 무기력해 하루가 걍 흘러가 불타다가 식어가 통제 규제 규칙 그딴 건 깨진 분위기나 쓸어가 끌리는 대로 매일매일 해 손에 잡히는 대로 내 일해 목표엔 내 것만을 대입해 나머진 싹 다 날려 허리케인 눈치만 보다가 뭣도 못 하잖아 시간만 흘러가는 중 고삐 풀린 망아지 나사 빠진 양아치 딱 그 전까지 막 나가는 중 STEP OUT 내가 원하는 대로 움직여 알아서들 Movin' 내키는 대로 내 앞을 가로막는 거대한 빙산 녹일 시간 없어 부숴 차가운 빙판 위에 미끄러져 넘어져도 두 어깨 툭툭 털고 일어서 전방에 큰 함성 소리로 'FREEZE' 땡 ICE ICE 얼음 얼음 땡 땡 두 손 머리 위로 (손 들어) 해방감을 느껴 (다 Turn up) 물총 술래 오기 전에 튀어 얼음 땡 얼음 땡 Free me 구속시켜 있던 날 해방시켜 Pressure back off 자꾸 뭐래 좀 빠져 있어 마치 Prison break 모든 걸 풀어 얼음 땡 룰 같은 건 걔나 줘 다 부숴버려라 Bang bang 달려나가 수갑 뺀 채로 얼려있던 내 몸 땡 때려 눈에 뵈는 게 없어 지금 이대로 승기를 한 손에 거머쥔 챔피언 그저 다 식겁하지 여유가 몸에 배 떡하니 동작 그만 칠전팔기 다 이겨낼 때까지 I'll keep rocking STEP OUT 내가 원하는 대로 움직여 알아서들 Movin' 내키는 대로 내 앞을 가로막는 거대한 빙산 녹일 시간 없어 부숴 차가운 빙판 위에 미끄러져 넘어져도 두 어깨 툭툭 털고 일어서 전방에 큰 함성 소리로 'FREEZE' 땡 ICE ICE 얼음 얼음 땡 땡 두 손 머리 위로 (손 들어) 해방감을 느껴 (다 Turn up) 물총 술래 오기 전에 튀어 얼음 땡 얼음 땡 I'm crossing the line 더는 못 참아 한 번 더 I break the ice 억눌렀던 말들 Just let it out 다시 또 I break the ice 뛰어 빙판이어도 Let it go 태워 심장의 불을 키워 Right now I'm getting out now 타올라 더 거침없이 뛰어 'FREEZE' 땡",
    "Un, deux, trois Run along with the gods, jumping between every verse The multiverse ain't ready for our universe (Jump, force) First, second, third, fourth wall We're breakin' them all, unbeatable score Our composition brings the competition But we've already won in this megaverse 바삐 또 굴리는 발바닥 바삐 또 굴리는 혓바닥 터뜨려 Pop, pop, pop, 어디든 섭렵해 싹 다 다 Popstar, festa, 안 꿇어 무르팍 무릎 팍 치고 머리 팍 치고 윽박지르던 놈들은 다 닥치고 공점일 초마다 돌려보는 컷 헛것이라도 본 듯 입이 떠억 Speechless, wordless I don't need your kindness 오직 내 걸 뱉고 나서야 속 편해 우리가 나왔다 (나와, 두두) 두 귀를 열어라 큰 대야를 준비해 그릇이 작으면 넘쳐흘러 감동의 눈물 Welcome to the Stray Kids Hot Megaverse (Hoo) Stray Kids (Hoo) Welcome to the Stray Kids Hot Megaverse Mic 잡았다 큰 거 하나 온다 떠받들어라 atlas 닥치는 대로 집어삼켜 소화해 모든 song form, megaverse 결말을 뻔하게 만들어 결국 끝을 보지, Megatron 영향력은 증폭돼 속삭여도 megaphone (Woah) 같이 모여 퍼뜨려 hooligans 몰아치게 놔둬 out of the way 헛소리는 입에 조준 철컥 We make the rules, nobody can hold me, yeah 안 듣고 못 배겨 들어보고 새겨 비켜 삥 둘러 봤자 바뀐 패권 chapter 다음 거 my word, power 올라가, high, 찍고 바로 random, ayy 올라가지 저 밑에서 발버둥 치다가 왔지, ayy Now 여기 위에서 말한 대로 내 위치는 top이지? Speechless, wordless 입 벌린 채 눈 둘 곳 없어 You know we're getting fearless, reckless 은하계에 울려 퍼지는 우리 음악 소리 Hey, 생각하는 대로 행동 우리 feel로 듣고 따라 우린 만들어 현실로 Every time we move The universe will follow Welcome to the Stray Kids Hot Megaverse (Hoo) Stray Kids (Hoo) Welcome to the Stray Kids Hot Megaverse 웅장한 내 목소리 you better run 이 정도의 스케일 측정 단위 megaton 웬만해선 절대 누구에게 안 꿀려 Stray Kids (Hoo) This our megaverse, big bang, your body shakes (Stray Kids everywhere all around the world) 'Cause we making bangers, yeah, yeah (Stray Kids everywhere all around the world) This our megaverse, big bang, everything shakes (Stray Kids everywhere all around the world) Welcome to the Stray Kids Hot Megaverse",
    "I see the ashes up in the sky 너의 목소리도 들리는 난 널 향해 손을 뻗어 봤자 얻는 건 공허한 마음 겁 없이 달리다 널 놓칠까 봐 I shout shout shout 수없이 불러 봐도 난 다시 한번 더 외쳐 난 너의 그림자처럼 붙어 있어도 so far far far 영원히 이렇게 지낼 수 없는 난 날 둘러싼 fauna and flora 먼지가 돼도 I really want you back 곁에 있던 fauna and flora 미안한 마음에 다시 쫓아가 now I'm catching up I'm catching up I can feel the rage burning up inside my heart Knowing you're no longer here I can't stop thinking about what I could've done But till this day, I live in fear I fell apart, burnt to the ground Got nothing but ashes in my eyes It's black and cold as night I wish I was there with you by your side I don't know if I can sleep well tonight  They tell me to keep movin' on Yeah I'll never be the same But I know that deep in my heart I'll carry all the pain 날 둘러싼 fauna and flora 먼지가 돼도 I really want you back 곁에 있던 fauna and flora 미안한 마음에 다시 쫓아가 now 겁 없이 달리다 널 놓칠까 봐 I shout shout shout 수없이 불러 봐도 난 다시 한번 더 외쳐 난 너의 그림자처럼 붙어 있어도 so far far far 영원히 이렇게 지낼 수 없는 난 I'm catching up I'm catching up 밤하늘을 봐도 난 눈을 감아도 너밖에 안 보여 달려가 쫓아가 불가능해도 oh I'm catching up (oh) I'm catching up (좀만 기다려 oh) I'm catching up (I'm catching up uh oh) 달려가 쫓아가 불가능해도 oh",
    "Lookin' at yourself A lot goes in your mind I don't know if I'm ready to show myself You worry day and night Look at the stars fall They leave the sky, goodbye Must be an oracle, like a waterfall They shower you with love tonight 'Cause you are You're perfect in my eyes You are Don't ever doubt yourself (You are) I know that feelin' too, I've been inside the dark I've never been so empty, hopeless (You are) But no, it isn't true 'Cause know that all the stars are by your side You know, whenever there's a chance I will tell you that you're amazin' as you are 'Cause when you give me a glance I am sure that I see the universe in your eyes Don't you ever tell yourself that you're not enough I am certain that you're truly fine You are a miracle, miracle, you are youtiful Let me tell a little story About the star that couldn't shine or blink Out of a million, billion Felt like an alien, alien Then that little star was surely Goin' to become the biggest thing Makin' a fantasy family Beautiful galaxy, galaxy 'Cause you are More than beautiful, one of a kind You are Just know I'm always by your side You know, whenever there's a chance I will tell you that you're amazin' as you are 'Cause when you give me a glance I am sure that I see the universe in your eyes Don't you ever tell yourself that you're not enough I am certain that you're truly fine You are a miracle, miracle, you are youtiful Another day ahead, don't wanna leave the bed You're lookin' at the mirror, see the tears covered in red I know that you've been cold this whole time But now I'm here to make it end You know, whenever there's a chance I will tell you that you're amazin' as you are (Amazin' as you are) 'Cause when you give me a glance I am sure that I see the universe in your eyes (Universe in your eyes) Don't you ever tell yourself that you're not enough I am certain that you're truly fine (Certain that you're truly fine) You are a miracle, miracle, you are youtiful",
    "How've you been? I guess you're fine It's been pretty long since we've last seen Honestly, throughout my life Deep inside, I never felt alive The way you used to touch my soul Was always so sweet and lovely No matter how far apart we were You'd always pick up the phone But now I'm truly all alone in this world I miss the way you felt so close to my bones I-I-I-I'm sinking in the deep end I'll just try-y-y-y to cry myself to sleep Please stop this pain If you hadn't changed, then I'd still be by your side If I gave you one more chance, can we go back again? You made me feel as if we were complete But now you're filled with nothing but conceit The times we had (Together) were bittersweet (Bittersweet) I miss the days we used to laugh and heal (Laugh and heal) The way you used to touch my soul Had always kept me whole You'd always read my text And ghost me like you wanted me gone Now I'm truly all alone in this world I miss the way you felt so close to my bones I-I-I-I'm sinking in the deep end I'll just try-y-y-y to cry myself to sleep Please stop this pain If you hadn't changed, then I'd still be by your side If I gave you one last chance, can we go back again? Honestly, without you in my life Deep inside, I've never felt alive ",
    "(Ooh) 어리숙하다니 이건 패기 젊은 피 (Ooh) 빈틈을 보여줄게 이건 여백의 미 (Ooh) 수많은 재능 no thanks 하나면 돼 master key 모든 색에 욕심 없어 골라 땄지 검은띠 겁 없이 눌러 스톱워치 시작해 당장 고민만 하다 답 없지 보이는 그대로 있는 그대로 가다 보면 펼쳐져 무한대로 Try me, judge me 'cause I don't give a 쉿 The way you look at my book cover, I ain't triggered by all means Embracing all my scars and imperfections Turn the tide all my cons are my pros now Flexing complexes just comflex Too bright I'm so flashy Different? No I'm unique That's right I'm so classy Nobody can stop me Complex 있는 대로 보여주지 다 comflex 만족하며 살아 쓸데없는 complain 흠도 매력이지 comfex, comflex 삐딱하게 비튼 고개 닿아 어깨 (어깨) 싸가지 바가지 말 많아도 내 솜씨에 (솜씨에) 박수가 절로 나와 이 정도의 결함은 있어 줘야 인간미가 있지 이게 내 comflex 뻥 차고 나가 단점은 내 강점 날 밟았다간 피 봐 난 육각형의 압정 약점이 내는 아우성에 더 각성해 감추기에 급급할 때 모두 까고 발전해 Try me, judge me 'cause I don't give a 쉿 The way you look at my book cover, I ain't triggered by all means Embracing all my scars and imperfections Turn the tide all my cons are my pros now Flexing complexes just comflex Too bright I'm so flashy (ooh) Different? No I'm unique (ooh) That's right I'm so classy (ooh)  can stop me Complex 있는 대로 보여주지 다 comflex 만족하며 살아 쓸데없는 complain 흠도 매력이지 comflex, comflex (ooh) Showing off my weakness, I'm not gonna hide it Look how shiny it is, this is my pride, got it? (Yeah) 없애지 않아도 it's so beautiful though 닦아내고 밝혀 (yeah, that is what I want) 모두 찌푸려도 신경은 불필요 Combine complex and flex, comflex Not being perfect is all it takes 'cause we're perfect Nothing can make the standard, show us some respect Not being perfect is all it takes 'cause we're perfect Love me the way I am Flexing complexes just comflex Too bright I'm so flashy (ooh) Different? No I'm unique (ooh) That's right I'm so classy (ooh) Nobody can stop me Complex 있는 대로 보여주지 다 comflex 만족하며 살아 쓸데없는 complain 흠도 매력이지 comflex, comflex (ooh)",
    "君を見るたびに 言葉すら出てこないさ マスク 50 枚してるみたい 気持ちを伝えなきゃダメなのに What to do? What to do? Oh, 体強張る 心だけ shake 君を見るたびに Heart is beating so loud ときめいてるさ ありのまま go Baby, you got me feelin' butterflies, butterflies 'Cause you're my only butterfly, butterfly 君だけのため 花咲かそう (Blooming flowers) Baby, you got me feelin' butterflies, butterflies 君の羽に倒されていい いつも同じ場所で見てんね (見てんね) Okay 言葉だけじゃ足りない 目の前の my ダイヤ 眩しくて惚れてしまうよ 一つの傑作 ピカピカ sign 溢れてる街中で 視線無視した my 羽ばたき 伝えられるか悩むことばっか 旅に出よう from this cocoon 君を見るたびに Heart is beating so loud ときめいてるさ ありのまま go Baby, you got me feelin' butterflies, butterflies 'Cause you're my only butterfly, butterfly 君だけのため 花咲かそう (Blooming flowers) Baby, you got me feelin' Butterflies, yeah, you got me shakin' everytime Butterfly, yeah, I want you to be by my side 踊りながら fly Don't you ever stop, you make me feel alive 遠回りして I'm falling 君しか見えない光景 準備できたら 君と一緒に alright 昼も夜も don't care 言葉噛んじゃっても噛み締めてゆこう 全て今ぶつけるんだ 君の手握って, one, two, three, let's go Butterflies, yeah, you got me shakin' everytime Butterfly, yeah, I want you to be by my side 踊りながら (Hey) Don't you ever stop (Aw) Baby, you got me feelin' butterflies, butterflies 君の羽に倒されていい いつも同じ場所で見てんね (見てんね)",
    "Slash 간결히 slash, 찰나에 터지는 spark 흐름을 끊었지 맥, 깊숙이 새겨진 mark 쳐도 돼, tap, 풀이 죽었지, pep 귀여워, pat, 넌 내 상대도 안 되지 쨉 손쉽게 처리해 어리석지 날 쉽게 봤다면 drop it 헛수고 멀리해 티끌을 모아서 태산도 chop it 약점은 안 보여 죽어도 안 죽어 근성은 zombie 자객이 들지 소문이 돌지 모두 섬칫 쥐도 새도 모르는 새 빠져나갈 구멍 없네 사정거리는 상하좌우 빈틈을 바랐다면 꿈 깨 Assassinate, quietly dominate 그림자 속에서 춤을 춰, right now, now I terminate, rise up, levitate 붉은 자객의 sword, 더 붉게 물들여 I'll color the night stars, the color of my heart 'Cause they'll be watching over me tonight Victorious silence, they know that I'm violence (Slash) 철컥, shing (Ching, ching) 현란하게 칼춤 추며 sing La-la-la, la (Ching, ching) 간결하게 slash 온몸에 붉게 타는 우리 색이 배일 때 반항할 수 없게 돼 so you better hack it 긴 말은 필요 없지 칼같이 slash it 간결하게 slash (Shing, shing, shing) Shh Come and get me, mission impossible 아무 기척 없이 소리 낮추고 슬금슬금 (슬금) 슬금슬금 (슬금) Piece of cake, wanna bet, okay, 콜 (콜) 별일 없이 wake up, 다음으로 weapons, check it, 해 현장 파괴범 함부로 뱉다가 싹 되려 다물고 결의에 찬 내게 환호성 하는 거 봐, 예술의 경지를 넘어섰다 신속히 쳐내지 장해물 뛰어넘어 버리는 모습에 모두가 와 (와) Assassinate, quietly dominate 그림자 속에서 춤을 춰, right now, now I terminate, rise up, levitate 붉은 자객의 sword, 더 붉게 물들여 I'll color the night stars, the color of my heart 'Cause they'll be watching over me tonight Victorious silence, they know that I'm violence (Slash) Slash (Ching, ching) Shing (Ching, ching) 현란하게 칼춤 추며 sing La-la-la, la (Ching, ching) 간결하게 slash 온몸에 붉게 타는 우리 색이 배일 때 반항할 수 없게 돼 so you better hack it (Slash) 긴 말은 필요 없지 칼같이 slash it 간결하게 slash (Shing, shing, shing)",
    "I'm walking my way, I'm walking my way I'm taking a step closer every day I'm climbing my way, I can't feel the pain Don't know where the end is so I cannot stop this I'm not gonna stay where I am, また前に向かって ゴールない階段だって 構わず上に上がって I don't think about giving up, 振り返れば崖 昇ったならば 振り返って 降りれない steps 君へと falling slowly 孤独と falling 慣れた痛み また耐えながら 乾いた地に咲き誇る flower 倒された瞬間に立ち上がる Push me off again I'm falling up, falling up, falling up And again, I'm falling up, falling up, falling up 血 汗 涙も head to the top 超えて昇る I got no slump I'm falling up, falling up, falling up And again, I'm falling 変わりゆく状況の中, I never change, I just follow me 信じるまま 気まま 進めばいい道の先 さらに高く届くように 火を独りで燃やし続け 高める闘志 (Yeah) 枯れた木に再び芽を出す, leaves 落ちたとしても変えられない, my dream 影なんて後ろにいるだけの thing 目の前暗くても「前」より明るい my street 君へと falling slowly 孤独と falling I'm falling up, falling up, falling up And again I'm falling up, falling up, falling up 血 汗 涙も head to the top 超えて昇る I got no slump I'm falling up, falling up, falling up And again, I'm falling Yeah, yeah, yeah I'm falling up, falling up, falling up (Falling up, falling up, falling up) 血 汗 涙も head to the top 超えて昇る I got no slump I'm falling up, falling up, falling up And again, I'm falling I'm falling up Yeah, yeah",
    "You're not alone Look at my shadow, I'm behind you like a ghost Mission 'Die A Legend'is a go The way I flow, taking all the shotsLanding free throws, beast mode Double snake eyes, turn 'em all to stone  And you're a student of war 내가 되갚을 때면 I'll leave you begging for more 뼛속 깊이 느껴 넌 그 문을 여는 순간 더이상 game은 없어 별다른 해답은 none 처음 맛보는 광경 Try me, I dare you to try me Took me long, but I'm here Coming down like lightning Taking back what's mine It was a matter of time If you wanna come play You gotta start with me And the monsters in my head In my head I got blood on my hands And you're my revenge And you push me to the edge The edge  Do you wanna come play? Te la viviste si en mí no creía' Llegamo' con el combo ready pa' hacerle' una avería-ía Cuida'o, que tengo mecha corta y puede que te explote la encía Prendo fuego y te quemo to'a la mercancía Mejor pedir perdón que pedir permiso, me la improviso Y a to'a esta gente le doy contra el piso Si quieren medir fuerza, les tengo un aviso Ma-mala suerte con la nena que dispara y preciso Try me, I dare you to try me Took me long, but I'm here Coming down like lightning Taking back what's mine It was a matter of time If you wanna come play You gotta start with me And the monsters in my head In my head (Yeah) I got blood on my hands And you're my revenge And you push me to the edge The edge Do you wanna come play? Hey, yeah, yeah, woo Do you wanna come play? (Do you wanna come play?) Yeah, yeah, woo If you wanna come play (If you wanna come play) You gotta start with me (Yeah) And the monsters in my head (Ayy, my head) In my head (Ayy, shout it out) I got blood on my hands (Got blood on my hands) And you're my revenge And you push me to the edge (Ayy, ayy) The edge (Yeah) Do you wanna come play?",
    "'네 손님' 어서 오십시오 이 가게는 참 메뉴가 고르기도 쉽죠 뭘 시켜도 오감을 만족하지 하지 지나가던 나그네, 비둘기까지 까치까지 까마귀들까지 Cooking a sauce 입맛대로 털어 음미하고 lick it 말해 bon Taste so good 반응은 모두 쩔어 But 모두 자극적인 거I want it till 다 먹일 때까지 연구하지 cross boundaries경계 따위 없어 마치 창조하듯 소리를 만들지 그저 계속 만들어가 새롭게 Because we're one of a kind 누구도 따라 할 수 없는 our own game 시작부터 다 우리 꺼 잠깐 떠나간다 해도 결국 다시 찾게 될 열기가 식지 않는 메뉴 지금부터 싹 다 입맛에다 때려 박아 DU DU DU DU DU DU 이게 우리 탕 탕 탕탕 DU DU DU DU DU DU 이게 우리 탕 탕 탕탕 지금 바로 눈에 불을 켜 I just wanna taste it, make it hot 새로운 불판 위에 track을 달궈 메뉴 골라 call me up 원하는 걸로 다 serve DU DU DU DU DU DU Cookin' like a chef I'm a 5 star 미슐랭 '미' 의 정점을 찍고 눈에 보여 illusion Whoo 첨 느꼈지 이런 감정놀랄 거야 gonna shock 바로 감전 자물쇠 따 싹 다 unlock Idea bank 머릿속을 털어 털어 비밀재료가 궁금하다면 사실 우린 그딴 거 안 써 그저 계속 만들어가 새롭게 Because we're one of a kind 누구도 따라 할 수 없는 our own game 시작부터 다 우리 꺼 잠깐 떠나간다 해도 결국 다시 찾게 될 열기가 식지 않는 메뉴 지금부터 싹 다 입맛에다 때려 박아 DU DU DU DU DU DU 뭐든 그냥 집어넣어 눈치 보지 말고 더 망설이지 말고 부어 비벼 비벼 '네 손님' DU DU DU 이게 우리 탕 탕 탕탕 DU DU DU DU DU DU 이게 우리 탕 탕 탕탕 DU DU DU DU DU DU 어서 오십시오 이 가게는 참 메뉴가 고르기도 쉽죠 뭘 시켜도 오감을 만족하지 하지 지나가던 나그네, 비둘기까지 까치까지 DU DU DU DU DU DU",
    "I sketch visions of my future But sometimes the wrong shades slip in the picture, feel like a failure, a loser But oh, my God, reminds me, I'm human Head high, I keep on moving living real, like Truman, I'm the true man We're all same, no difference Fail, fear, bad days make me more different, I born freak This is my own movement We don't care 'cause we are blessed I don't play, you know, we keep it hundred Cop, coppin' all that shit, whenever I want it (Ooh, ooh) It's that, it's that beast mode as Rengar calls it Got trophies in the bag, 'cause of STAY, we lock in (Yeah, yeah) Ride a Benz, raise my hands, salute fans Gas is running, hit the pedal, we going fast We so advanced, we the first and the last We so advanced, we the first and the last Woke up 5AM, tryna catch a plane, we don't waste time Since I was a kid, young ambitions got me out of school No more following orders, now I make my own rules Still got that fire, bright and shining like a jewel (Yeah) This is our crew, (Okay) we'll show what's new (What's new?) We got the juice, (Woo) we got the moves (Yeah, yeah) Let's groove tonight, alright, got LV shoes You wouldn't know what I'm about (Let's go, ayy) Working our way up, we go (Go) Cooking up races, I know that we taking our time like Charles Leclerc (Woo) I masticate all of my enemies Call me Pac-Man, I eat up the road (Grr) I'll finish you like I eat the last chip in the bag Like you got nothing to show, that's how I roll I don't play, you know, we keep it hundred Cop, coppin' all that shit whenever I want it It's that, it's that beast mode as Rengar calls it Got trophies in the bag, 'cause of STAY, we lock in (Yeah, yeah) Ride a Benz, raise my hands, salute fans Gas is running, hit the pedal, we going fast We so advanced, we the first and the last We so advanced, we the first and the last (Yeah) Way out punk 구태의연한 척 하품 나오기일수 no 배려 텅 (Ah) 빈 그릇 코 박고 practice what you doin' now, 차렷 son 꼭두각시 행세에 배 잡고 웃음도 참아, you done? (You done?) Okay, okay, you said it's fancy, I can see your 뻥 (Ah) 껌뻑 하면 떨어지는 쟤들은 펑펑 (펑펑) Look at you, 했었잖아 말을 떵떵 Lotta pain but I keep my 태도 비수에 싹 토해내고 jump up (Oh) Lay down, 내 선은 비스듬, this system full of wisdom Don't tryna follow us, long distance Our eyes, 여전히 shine crimson I don't play, you know, we keep it hundred Cop coppin' all that shit whenever I want it It's that, it's that beast mode as Rengar calls it Got trophies in the bag 'cause of STAY, we lock in (Yeah, yeah) Ride a Benz, raise my hands, salute fans Gas is running, hit the pedal, we going fast We so advanced, we the first and the last We so advanced, we the first and the last Yeah, woo Hey Yeah, yeah, yeah, yeah Hey",
    
];
let generates = function (a, ){
    let mk =
        getRandomWord(a) +
    ""
    return mk;
};
let TXTS = [
"너를 만나 몰랐던 네 맘의 의미를 배워 가 (배워 가) All day and night (Night) 세상이 온통 너야  내 시선들의 춤 끝엔 늘 your ways 세상의 장면 중 네게만 반응해 단어를 뺏긴 듯 (뺏긴 듯) lost in translation (Lost in translation) 알잖아 이건 언어 이상의 signs, ah 어린애처럼 (Yeah), 가나다라 배워 가는 나, yeah, yeah I'm down for you (I'm down for you), 생각해 종일 너만, mm Baby, just tell me, I can't read your mind What's your love language?  What's your love language? 너를 더 알고 싶어 What's your love language? 너를 말하고 싶어 Tea-tea-teach me All about your love language (Love language?) 점점 깊이 (More) 알고 싶어 너의 language (What's your love language?)  Yeah, 살짝 스친 손도 (손도) 익숙한 단어도 (Your world) 다른 뜻이 있을까 고민에 빠져 또 (Oh-oh) 연구해 you-ology, 너에 대한 A to Z 의미를 사전처럼 해독하고 싶어, baby 너의 이름이 (Yeah) 낙원의 또 다른 말 같아, yeah, yeah (Ah-ah) I'm down for you (I'm down for you, woo), 생각해 종일 너만 (Mm) Baby, just tell me, I can't read your mind (Ooh-ooh) What's your love language? (Language, ooh) What's your love language? 너를 더 알고 싶어 (Want to ya, your love like that) What's your love language? 너를 말하고 싶어 Lonely, 길 잃은 나의 night Promise, 날 이끌어 준 light My everything, 들려줄게 네게 (All about love, babe) What's your love language? What's your love language? 너를 다 알고 싶어 (싶어) What's your love language? (Language) 너를 말하고 싶어 Tea-tea-teach me All about your love language (Love language) 점점 깊이 (More) 알고 싶어 너의 language (Love language) Tea-tea-teach me All about your love language (All about your love language; Love language)점점 깊이 (Oh-oh) 알고 싶어 너의 language (What's your love language?)",

]
stay.addEventListener("click", function () {
    let ok = generateK(stray, );
    output.textContent = ok;
});
let t = document.getElementById("TXT");
let ts = function(a, ){
    let mk =
        getRandomWord(a) +
    ""
    return mk;
};
t.addEventListener("click", function () {
    let ok = generateK(TXTS, );
    output.textContent = ok;
});